/* Non-destructive integration with Savanski CanvasEngine brush dynamics. */
(function(w){'use strict';
const $=q=>document.querySelector(q),state={all:[],chosen:null,image:null,colored:null,colorKey:'',style:'',rotation:16,sizeJitter:.12,tilt:false,symmetry:'none'};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const desc=$('#svBrushPreview'),family=$('#svBrushFamily'),grid=$('#svBrushLibrary');
function studio(){return w.LFStudio?.engine}
function inform(str){if(desc)desc.textContent=str}
function option(name,fn){const el=$(`[data-sv-option="${name}"]`);if(!el)return;const handler=()=>fn(el.type==='checkbox'?el.checked:el.value);el.addEventListener('input',handler);el.addEventListener('change',handler);handler()}
function markSelected(b){grid?.querySelectorAll('button').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.brushId===b.id)))}
function recolor(){const im=state.image,e=studio();if(!im||!e)return null;const col=e.primary||'#000000';if(state.colored&&state.colorKey===col)return state.colored;const cv=document.createElement('canvas');cv.width=im.naturalWidth||im.width;cv.height=im.naturalHeight||im.height;const ctx=cv.getContext('2d');ctx.drawImage(im,0,0);ctx.globalCompositeOperation='source-in';ctx.fillStyle=col;ctx.fillRect(0,0,cv.width,cv.height);ctx.globalCompositeOperation='source-over';state.colored=cv;state.colorKey=col;return cv}
async function choose(b){const e=studio();if(!e){inform('Open a canvas to select brushes.');return}state.chosen=b;state.style='';state.image=null;state.colored=null;state.colorKey='';const im=new Image();im.onload=()=>{if(state.chosen!==b)return;state.image=im;state.colored=null;inform(b.name+' • '+b.family+' • ready to paint');};im.onerror=()=>inform('Brush image unavailable: '+b.name);im.src=b.path;e.setTool('brush');e.brushTip='texture';e.brushSpacing=b.spacing??.18;e.brushScatter=b.scatter??.12;e.brushFlow=b.flow??.85;markSelected(b)}
function renderList(){if(!grid||!family)return;const group=family.value;grid.replaceChildren();let count=0;for(const brush of state.all){if(group!=='all'&&brush.family!==group)continue;const b=document.createElement('button');b.type='button';b.className='sv-brush-item';b.dataset.brushId=brush.id;b.title=brush.name;b.setAttribute('aria-label','Use '+brush.name);b.setAttribute('aria-pressed',String(state.chosen?.id===brush.id));const img=document.createElement('img');img.src=brush.path;img.alt='';img.loading='lazy';const label=document.createElement('span');label.textContent=brush.name;b.append(img,label);b.addEventListener('click',()=>choose(brush));grid.append(b);if(++count>=240)break}}
async function initLibrary(){try{const res=await fetch('json/brush-library.json');if(!res.ok)throw Error('Library unavailable');state.all=await res.json();const groups=[...new Set(state.all.map(x=>x.family))].sort();family.replaceChildren(new Option('All brushes','all'),...groups.map(g=>new Option(g,g)));family.addEventListener('change',renderList);renderList();inform(state.all.length+' texture brushes ready. Select any tip to paint.')}catch(e){inform('Brush library unavailable; built-in brushes still work.')}}
function dab(ctx,cx,cy,size,alpha,angle,base){const e=studio();if(!e)return base(ctx,cx,cy,size,alpha,angle);
 if(state.chosen&&state.image){const img=recolor();if(img){ctx.save();ctx.translate(cx,cy);ctx.rotate(angle);ctx.globalAlpha=clamp(alpha,0,1);ctx.drawImage(img,-size/2,-size/2,size,size);ctx.restore();return}}
 const kind=state.style;
 if(!kind)return base(ctx,cx,cy,size,alpha,angle);
 ctx.save();ctx.translate(cx,cy);ctx.rotate(angle);ctx.fillStyle=e.primary||'#000000';ctx.strokeStyle=e.primary||'#000000';ctx.globalAlpha=alpha;
 if(kind==='ribbon'){ctx.lineWidth=Math.max(1,size*.12);for(let k=-2;k<=2;k++){ctx.beginPath();ctx.moveTo(-size*.5,k*size*.16);ctx.bezierCurveTo(-size*.14,size*.22+k*size*.14,size*.14,-size*.22+k*size*.14,size*.5,k*size*.16);ctx.stroke()}}
 if(kind==='glitter'){for(let i=0;i<8;i++){let x=(Math.random()-.5)*size,y=(Math.random()-.5)*size,r=size*(.02+Math.random()*.085);ctx.beginPath();ctx.moveTo(x-r,y);ctx.lineTo(x+r,y);ctx.moveTo(x,y-r);ctx.lineTo(x,y+r);ctx.lineWidth=Math.max(1,r*.45);ctx.stroke()}}
 if(kind==='confetti'){for(let i=0;i<7;i++){const x=(Math.random()-.5)*size,y=(Math.random()-.5)*size,r=size*(.04+Math.random()*.08);ctx.fillRect(x,y,r,r*.55)}}
 if(kind==='braid'){ctx.lineWidth=Math.max(1,size*.11);for(let i=-1;i<=1;i++){ctx.beginPath();ctx.moveTo(-size*.5,i*size*.15);ctx.quadraticCurveTo(0,(-i)*size*.35,size*.5,i*size*.15);ctx.stroke()}}
 ctx.restore()}
function enginePatch(){if(!w.LFCanvasEngine)return setTimeout(enginePatch,80);const proto=w.LFCanvasEngine.prototype;if(proto.__svAdvancedBrushes)return;proto.__svAdvancedBrushes=true;
const original=proto.paintDab,step=proto.paintDynamicDabs;
proto.paintDab=function(ctx,x,y,size,alpha,angle=0){const scaled=size*(1+((state.chosen||state.style)?(Math.random()*2-1)*state.sizeJitter:0));return dab(ctx,x,y,Math.max(1,scaled),alpha,angle,original.bind(this))};
proto.paintDynamicDabs=function(ctx,a,b,size,alpha,first){if(state.symmetry==='none'||(!state.chosen&&!state.style))return step.call(this,ctx,a,b,size,alpha,first);const axes=state.symmetry;const pts=[[1,1]];if(axes==='vertical'||axes==='four')pts.push([-1,1]);if(axes==='horizontal'||axes==='four')pts.push([1,-1]);if(axes==='four')pts.push([-1,-1]);for(const [mx,my] of pts){const cx=this.width/2,cy=this.height/2;const p={x:mx>0?a.x:2*cx-a.x,y:my>0?a.y:2*cy-a.y},q={x:mx>0?b.x:2*cx-b.x,y:my>0?b.y:2*cy-b.y};ctx.save();if(mx<0||my<0){/* mirrored placements already transformed as points */}step.call(this,ctx,p,q,size,alpha,first);ctx.restore()}};
}
function init(){enginePatch();initLibrary();option('spacing',v=>{const e=studio();if(e)e.brushSpacing=+v});option('scatter',v=>{const e=studio();if(e)e.brushScatter=+v});option('angle',v=>{state.rotation=+v;const e=studio();if(e)e.brushAngleJitter=+v});option('sizeJitter',v=>state.sizeJitter=+v);option('flow',v=>{const e=studio();if(e)e.brushFlow=+v});option('symmetry',v=>state.symmetry=v);option('pressure',v=>{const e=studio();if(e)e.brushPressure=v});option('tilt',v=>state.tilt=v);
$('#svBrushImport')?.addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/'))return inform('Choose PNG, JPEG or WebP.');if(file.size>5_000_000)return inform('Brush PNG must be under 5 MB.');const reader=new FileReader();reader.onload=()=>choose({id:'imported',name:file.name,family:'Imported',path:reader.result,spacing:.18,scatter:.04});reader.readAsDataURL(file)});
w.addEventListener('savanski:tool',e=>{const n=e.detail?.action||'';const map={'advanced-texture-brush':'texture','advanced-ribbon-brush':'ribbon','advanced-glitter-brush':'glitter','advanced-confetti-brush':'confetti','advanced-braid-brush':'braid'};if(!(n in map))return;const engine=studio();if(!engine)return;if(n!=='advanced-texture-brush'){state.chosen=null;state.image=null;state.style=map[n];engine.brushTip='texture';engine.brushScatter=.07;engine.brushSpacing=.14;inform(map[n][0].toUpperCase()+map[n].slice(1)+' brush ready')}else{state.style='';if(!state.chosen)inform('Select a texture brush tip from Brush Lab.')}engine.setTool('brush')});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
w.SavanskiAdvancedBrushes={state,choose};
})(window);
