(function(){
'use strict';
const S=window.Savanski,st=S.state;
function keys(layerId){return st.animation.keyframes[layerId]||(st.animation.keyframes[layerId]=[])}
S.animationTransform=function(layerId,frame){const arr=[...keys(layerId)].sort((a,b)=>a.frame-b.frame);const base={x:0,y:0,scale:1,rotation:0,opacity:1};if(!arr.length)return base;if(frame<=arr[0].frame)return{...base,...arr[0]};if(frame>=arr.at(-1).frame)return{...base,...arr.at(-1)};let a=arr[0],b=arr.at(-1);for(let i=0;i<arr.length-1;i++)if(frame>=arr[i].frame&&frame<=arr[i+1].frame){a=arr[i];b=arr[i+1];break}const t=(frame-a.frame)/Math.max(1,b.frame-a.frame),lerp=(x,y)=>x+(y-x)*t;return{x:lerp(a.x??0,b.x??0),y:lerp(a.y??0,b.y??0),scale:lerp(a.scale??1,b.scale??1),rotation:lerp(a.rotation??0,b.rotation??0),opacity:lerp(a.opacity??1,b.opacity??1)}};
S.addKeyframe=function(){const l=S.activeLayer();if(!l){S.toast('Choose a layer first.','error');return}const frame=S.clamp(+S.$('#animFrame').value||0,0,st.animation.frames-1),k={frame,x:+S.$('#animX').value||0,y:+S.$('#animY').value||0,scale:Math.max(.01,+S.$('#animScale').value||1),rotation:+S.$('#animRotation').value||0,opacity:(+S.$('#animOpacity').value||100)/100};const arr=keys(l.id),i=arr.findIndex(x=>x.frame===frame);if(i>=0)arr[i]=k;else arr.push(k);arr.sort((a,b)=>a.frame-b.frame);S.syncAnimationProject();S.renderKeyframes();S.autosave?.();S.toast(`Keyframe added at ${frame}`,'success')};
S.removeKeyframe=function(){const l=S.activeLayer();if(!l)return;const frame=+S.$('#animFrame').value||0,arr=keys(l.id),i=arr.findIndex(x=>x.frame===frame);if(i>=0){arr.splice(i,1);S.syncAnimationProject();S.renderKeyframes();S.autosave?.()}};
S.renderKeyframes=function(){const box=S.$('#keyframeList'),l=S.activeLayer();if(!box)return;box.innerHTML='';if(!l)return;for(const k of keys(l.id)){const d=document.createElement('div');d.className='keyframe-item';d.innerHTML=`<b>Frame ${k.frame}</b> · x ${k.x} · y ${k.y} · scale ${k.scale.toFixed(2)} · rot ${k.rotation}° · opacity ${Math.round(k.opacity*100)}%`;d.onclick=()=>{S.$('#animFrame').value=k.frame;S.$('#animFrameOut').value=k.frame;S.$('#animX').value=k.x;S.$('#animY').value=k.y;S.$('#animScale').value=k.scale;S.$('#animRotation').value=k.rotation;S.$('#animOpacity').value=Math.round(k.opacity*100);S.renderAnimationFrame(k.frame)};box.append(d)}};
S.syncAnimationProject=function(){if(!st.project)return;st.project.animation={frames:st.animation.frames,fps:st.animation.fps,keyframes:structuredClone(st.animation.keyframes)}};
S.renderAnimationFrame=function(frame,target=null){frame=S.clamp(Math.round(frame),0,st.animation.frames-1);st.animation.frame=frame;S.renderLayers(target||S.$('#viewCanvas'),{frame,grid:st.map.exportGrid&&st.map.enabled&&st.map.gridType!=='none'});if(!target)S.$('#animFrameOut').value=frame};
S.previewAnimation=async function(){if(st.animation.playing)return;st.animation.playing=true;st.animation.stop=false;const fps=st.animation.fps=Math.max(1,Math.min(60,+S.$('#animFps').value||30)),frames=st.animation.frames=Math.max(2,Math.min(600,+S.$('#animFrames').value||90));S.$('#animFrame').max=frames-1;S.syncAnimationProject();for(let f=0;f<frames&&!st.animation.stop;f++){S.$('#animFrame').value=f;S.renderAnimationFrame(f);await S.sleep(1000/fps)}st.animation.playing=false;S.renderLayers()};
S.stopAnimation=function(){st.animation.stop=true;st.animation.playing=false;S.renderLayers()};
S.exportWebM=async function(){if(!window.MediaRecorder){S.toast('This browser does not support WebM recording.','error');return}const p=st.project,fps=Math.max(1,Math.min(60,+S.$('#animFps').value||30)),frames=Math.max(2,Math.min(600,+S.$('#animFrames').value||90)),c=document.createElement('canvas');c.width=p.width;c.height=p.height;const stream=c.captureStream(fps),types=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'];const type=types.find(t=>MediaRecorder.isTypeSupported(t))||'';const rec=new MediaRecorder(stream,type?{mimeType:type,videoBitsPerSecond:Math.min(25000000,Math.max(4000000,p.width*p.height*fps*.08))}:undefined),chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};const done=new Promise(r=>rec.onstop=r);rec.start();S.status('Recording animation…');for(let f=0;f<frames;f++){S.renderAnimationFrame(f,c);await S.sleep(1000/fps)}rec.stop();await done;const blob=new Blob(chunks,{type:rec.mimeType||'video/webm'});S.downloadBlob(blob,S.safeName(p.name,'.webm'));S.renderLayers();S.toast(`Exported ${S.formatBytes(blob.size)} WebM`,'success')};
S.configureAnimation=function(){st.animation.frames=Math.max(2,Math.min(600,+S.$('#animFrames').value||90));st.animation.fps=Math.max(1,Math.min(60,+S.$('#animFps').value||30));S.$('#animFrame').max=st.animation.frames-1;S.syncAnimationProject()};
})();
