(function(){
'use strict';
const clamp=(v,a=0,b=255)=>Math.max(a,Math.min(b,v));
function hex(hex){const h=hex.replace('#','');const n=parseInt(h.length===3?h.split('').map(x=>x+x).join(''):h,16);return [(n>>16)&255,(n>>8)&255,n&255,255]}
function activeRaster(engine){const l=engine.activeLayer();if(!l||l.locked)return null;return l}
function destructive(engine,label,fn){const l=activeRaster(engine);if(!l)return false;const snap=engine.history.capture(label);fn(l.canvas,l);engine.history.push(snap);engine.render();return true}
function cssFilter(canvas,filter){const t=document.createElement('canvas');t.width=canvas.width;t.height=canvas.height;const x=t.getContext('2d');x.filter=filter;x.drawImage(canvas,0,0);const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);c.drawImage(t,0,0)}
function convolution(canvas,kernel,divisor=1,bias=0){const x=canvas.getContext('2d',{willReadFrequently:true}),im=x.getImageData(0,0,canvas.width,canvas.height),out=x.createImageData(im.width,im.height),d=im.data,o=out.data,w=im.width,h=im.height,s=Math.sqrt(kernel.length)|0,half=s>>1;for(let y=0;y<h;y++)for(let x0=0;x0<w;x0++){let rr=0,gg=0,bb=0,aa=d[(y*w+x0)*4+3];for(let ky=0;ky<s;ky++)for(let kx=0;kx<s;kx++){const sx=Math.max(0,Math.min(w-1,x0+kx-half)),sy=Math.max(0,Math.min(h-1,y+ky-half)),i=(sy*w+sx)*4,k=kernel[ky*s+kx];rr+=d[i]*k;gg+=d[i+1]*k;bb+=d[i+2]*k}const j=(y*w+x0)*4;o[j]=clamp(rr/divisor+bias);o[j+1]=clamp(gg/divisor+bias);o[j+2]=clamp(bb/divisor+bias);o[j+3]=aa}x.putImageData(out,0,0)}
function getRegion(canvas,a,b,size){const minX=Math.max(0,Math.floor(Math.min(a.x,b.x)-size)),minY=Math.max(0,Math.floor(Math.min(a.y,b.y)-size)),maxX=Math.min(canvas.width,Math.ceil(Math.max(a.x,b.x)+size)),maxY=Math.min(canvas.height,Math.ceil(Math.max(a.y,b.y)+size));return {x:minX,y:minY,w:maxX-minX,h:maxY-minY}}
const api={
 floodFill(canvas,sx,sy,color,alpha=1,tolerance=18){const ctx=canvas.getContext('2d',{willReadFrequently:true}),w=canvas.width,h=canvas.height;if(sx<0||sy<0||sx>=w||sy>=h)return;const img=ctx.getImageData(0,0,w,h),d=img.data,start=(sy*w+sx)*4,target=[d[start],d[start+1],d[start+2],d[start+3]],fill=hex(color);fill[3]=Math.round(255*alpha);if(target.every((v,i)=>Math.abs(v-fill[i])<2))return;const match=i=>Math.abs(d[i]-target[0])<=tolerance&&Math.abs(d[i+1]-target[1])<=tolerance&&Math.abs(d[i+2]-target[2])<=tolerance&&Math.abs(d[i+3]-target[3])<=tolerance;const seen=new Uint8Array(w*h),stack=[[sx,sy]];let visited=0,max=Math.min(w*h,14000000);while(stack.length&&visited++<max){const [x,y]=stack.pop(),pi=y*w+x;if(seen[pi])continue;seen[pi]=1;const i=pi*4;if(!match(i))continue;d[i]=fill[0];d[i+1]=fill[1];d[i+2]=fill[2];d[i+3]=fill[3];if(x>0)stack.push([x-1,y]);if(x<w-1)stack.push([x+1,y]);if(y>0)stack.push([x,y-1]);if(y<h-1)stack.push([x,y+1])}ctx.putImageData(img,0,0)},
 localBrush(canvas,a,b,size,kind,opacity){const r=getRegion(canvas,a,b,size),ctx=canvas.getContext('2d',{willReadFrequently:true});if(r.w<1||r.h<1)return;const patch=document.createElement('canvas');patch.width=r.w;patch.height=r.h;const px=patch.getContext('2d');px.drawImage(canvas,r.x,r.y,r.w,r.h,0,0,r.w,r.h);if(kind==='blur-brush'||kind==='smudge')cssFilter(patch,kind==='smudge'?'blur(7px)':'blur(4px)');if(kind==='sharpen-brush')convolution(patch,[0,-1,0,-1,5,-1,0,-1,0]);if(kind==='dodge'||kind==='burn')cssFilter(patch,kind==='dodge'?'brightness(1.22)':'brightness(.78)');ctx.save();ctx.globalAlpha=opacity;ctx.drawImage(patch,r.x,r.y);ctx.restore()},
 applyFilter(engine,name,value){return destructive(engine,name,(canvas)=>{switch(name){case'brightness':cssFilter(canvas,`brightness(${value})`);break;case'contrast':cssFilter(canvas,`contrast(${value})`);break;case'saturation':cssFilter(canvas,`saturate(${value})`);break;case'hue':cssFilter(canvas,`hue-rotate(${value}deg)`);break;case'grayscale':cssFilter(canvas,'grayscale(1)');break;case'sepia':cssFilter(canvas,'sepia(1)');break;case'invert':cssFilter(canvas,'invert(1)');break;case'blur':cssFilter(canvas,`blur(${value||3}px)`);break;case'sharpen':convolution(canvas,[0,-1,0,-1,5,-1,0,-1,0]);break;case'clarity':convolution(canvas,[-1,-1,-1,-1,9,-1,-1,-1,-1]);break;case'dehaze':cssFilter(canvas,'contrast(1.18) saturate(1.08)');break;case'auto-enhance':cssFilter(canvas,'contrast(1.08) saturate(1.06) brightness(1.02)');break;case'vintage':cssFilter(canvas,'sepia(.45) saturate(.8) contrast(1.05)');break;case'cool':cssFilter(canvas,'saturate(.95) hue-rotate(8deg) brightness(1.02)');break;case'warm':cssFilter(canvas,'sepia(.12) saturate(1.1)');break;case'noir':cssFilter(canvas,'grayscale(1) contrast(1.25)');break;case'fade':cssFilter(canvas,'contrast(.86) saturate(.78) brightness(1.08)');break;case'unblur':convolution(canvas,[0,-1,0,-1,5.6,-1,0,-1,0],1.6);break;default:break}})},
 autoLevels(engine){return destructive(engine,'Auto Levels',canvas=>{const ctx=canvas.getContext('2d',{willReadFrequently:true}),im=ctx.getImageData(0,0,canvas.width,canvas.height),d=im.data;let lo=255,hi=0;for(let i=0;i<d.length;i+=4){if(d[i+3]===0)continue;const y=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2];lo=Math.min(lo,y);hi=Math.max(hi,y)}const span=Math.max(1,hi-lo);for(let i=0;i<d.length;i+=4){for(let c=0;c<3;c++)d[i+c]=clamp((d[i+c]-lo)*255/span)}ctx.putImageData(im,0,0)})},
 grain(engine,amount=.08){return destructive(engine,'Grain',canvas=>{const ctx=canvas.getContext('2d',{willReadFrequently:true}),im=ctx.getImageData(0,0,canvas.width,canvas.height),d=im.data,a=255*amount;for(let i=0;i<d.length;i+=4){const n=(Math.random()-.5)*a;d[i]=clamp(d[i]+n);d[i+1]=clamp(d[i+1]+n);d[i+2]=clamp(d[i+2]+n)}ctx.putImageData(im,0,0)})},
 pixelate(engine,size=12){return destructive(engine,'Pixelate',canvas=>{const small=document.createElement('canvas');small.width=Math.max(1,Math.round(canvas.width/size));small.height=Math.max(1,Math.round(canvas.height/size));const s=small.getContext('2d');s.imageSmoothingEnabled=false;s.drawImage(canvas,0,0,small.width,small.height);const x=canvas.getContext('2d');x.clearRect(0,0,canvas.width,canvas.height);x.imageSmoothingEnabled=false;x.drawImage(small,0,0,canvas.width,canvas.height);x.imageSmoothingEnabled=true})},
 vignette(engine,strength=.45){return destructive(engine,'Vignette',canvas=>{const x=canvas.getContext('2d'),g=x.createRadialGradient(canvas.width/2,canvas.height/2,Math.min(canvas.width,canvas.height)*.18,canvas.width/2,canvas.height/2,Math.max(canvas.width,canvas.height)*.68);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(1,`rgba(0,0,0,${strength})`);x.fillStyle=g;x.fillRect(0,0,canvas.width,canvas.height)})},
 duotone(engine,c1='#1c1c6b',c2='#ffbd59'){return destructive(engine,'Duotone',canvas=>{const a=hex(c1),b=hex(c2),ctx=canvas.getContext('2d',{willReadFrequently:true}),im=ctx.getImageData(0,0,canvas.width,canvas.height),d=im.data;for(let i=0;i<d.length;i+=4){const y=(.2126*d[i]+.7152*d[i+1]+.0722*d[i+2])/255;d[i]=a[0]*(1-y)+b[0]*y;d[i+1]=a[1]*(1-y)+b[1]*y;d[i+2]=a[2]*(1-y)+b[2]*y}ctx.putImageData(im,0,0)})},
 removeSolidBackground(engine,tolerance=34){return destructive(engine,'Remove Background',canvas=>{const ctx=canvas.getContext('2d',{willReadFrequently:true}),im=ctx.getImageData(0,0,canvas.width,canvas.height),d=im.data,w=canvas.width,h=canvas.height;const samples=[[0,0],[w-1,0],[0,h-1],[w-1,h-1]].map(([x,y])=>{const i=(y*w+x)*4;return[d[i],d[i+1],d[i+2]]});const bg=samples.reduce((a,s)=>a.map((v,i)=>v+s[i]/samples.length),[0,0,0]);for(let i=0;i<d.length;i+=4){const dist=Math.hypot(d[i]-bg[0],d[i+1]-bg[1],d[i+2]-bg[2]);if(dist<tolerance)d[i+3]=0;else if(dist<tolerance*2)d[i+3]=Math.round(d[i+3]*(dist-tolerance)/tolerance)}ctx.putImageData(im,0,0)})},
 makeTransparentByColor(engine,color,tolerance=32){const tgt=hex(color);return destructive(engine,'Color to Transparent',canvas=>{const ctx=canvas.getContext('2d',{willReadFrequently:true}),im=ctx.getImageData(0,0,canvas.width,canvas.height),d=im.data;for(let i=0;i<d.length;i+=4){const dist=Math.hypot(d[i]-tgt[0],d[i+1]-tgt[1],d[i+2]-tgt[2]);if(dist<tolerance)d[i+3]=0}ctx.putImageData(im,0,0)})},
 resizeLayerToFit(engine,mode='contain'){const l=activeRaster(engine);if(!l)return false;const snap=engine.history.capture('Fit Layer');const src=document.createElement('canvas');src.width=engine.width;src.height=engine.height;src.getContext('2d').drawImage(l.canvas,0,0);const ctx=l.canvas.getContext('2d');ctx.clearRect(0,0,engine.width,engine.height);if(mode==='cover')ctx.drawImage(src,0,0,engine.width,engine.height);else ctx.drawImage(src,0,0,engine.width,engine.height);engine.history.push(snap);engine.render();return true}
};
window.LFImageTools=api;
})();
