(function(global){
'use strict';
const $=(s,r=document)=>r.querySelector(s);let shapeData=null,brushData=null,kind='shape',offset=0;const PAGE=48;
async function load(type){const status=$('#catalogStatus');status.textContent='Loading preset data…';try{if(type==='shape'&&!shapeData){const r=await fetch('json/procedural-shape-catalog.json');if(!r.ok)throw new Error('shape catalog '+r.status);shapeData=await r.json()}if(type==='brush'&&!brushData){const r=await fetch('json/brush-dynamics-catalog.json');if(!r.ok)throw new Error('brush catalog '+r.status);brushData=await r.json()}status.textContent=type==='shape'?`${shapeData.shapes.length.toLocaleString()} vector shapes`:`${brushData.presets.length.toLocaleString()} brush presets`;render()}catch(e){status.textContent='Preset catalog requires the Studio to be served over HTTP/HTTPS.';console.warn(e)}}
function current(){return kind==='shape'?(shapeData?.shapes||[]):(brushData?.presets||[])}
function filtered(){const q=($('#catalogSearch')?.value||'').trim().toLowerCase();if(!q)return current();return current().filter(x=>(x.name+' '+(x.family||'')+' '+(x.kind||'')+' '+(x.nib||'')).toLowerCase().includes(q))}
function render(){const wrap=$('#catalogResults');if(!wrap)return;const arr=filtered(),start=Math.min(offset,Math.max(0,arr.length-1)),items=arr.slice(start,start+PAGE);wrap.innerHTML='';for(const item of items){const b=document.createElement('button');b.className='catalog-card';const title=document.createElement('strong');title.textContent=item.name;const small=document.createElement('span');small.textContent=kind==='shape'?`${item.family} · ${item.points.length} vector points`:`${item.kind} · ${item.nib} nib · ${item.size}px`;b.append(title,small);b.addEventListener('click',()=>kind==='shape'?addShape(item):applyBrush(item));wrap.append(b)}$('#catalogPager').textContent=arr.length?`${(start+1).toLocaleString()}–${Math.min(start+PAGE,arr.length).toLocaleString()} of ${arr.length.toLocaleString()}`:'No matching presets'}
function addShape(item){const ctl=global.LFAdvancedController;if(!ctl?.engine?.project)return;const w=ctl.engine.width*.32,h=ctl.engine.height*.32;const o=ctl.store.add('shape',{name:item.name,geometry:{x:(ctl.engine.width-w)/2,y:(ctl.engine.height-h)/2,width:w,height:h,shape:'custom',customPath:item.points.map(([x,y])=>({x,y}))},style:{fill:ctl.engine.secondary||'#fff',stroke:ctl.engine.primary||'#000',strokeWidth:Math.max(1,ctl.engine.width/600),opacity:ctl.engine.opacity??1}});ctl.store.select(o.id);ctl.savedShapePreset={shape:'custom',customPath:o.geometry.customPath.map(p=>({...p}))};ctl.openInspector();global.LFStudio?.toast?.('Vector shape added; it is also ready as a crop or brush-shape preset.')}
function applyBrush(item){const ctl=global.LFAdvancedController;if(!ctl)return;const nib=item.nib==='custom'&&!ctl.savedShapePreset?'circle':item.nib;global.LFBrushPresetActive={...item,nib,nibCustomPath:nib==='custom'?ctl.savedShapePreset?.customPath:null};ctl.engine.brushSize=item.size;ctl.engine.opacity=item.opacity;ctl.engine.setTool(item.kind==='spray'?'airbrush':item.kind);const o=ctl.store.selected();if(o&&(o.type==='stroke'||o.type==='eraser-stroke'))ctl.store.update(o.id,{style:{brushKind:item.kind,size:item.size,opacity:item.opacity,nibShape:nib,nibCustomPath:global.LFBrushPresetActive.nibCustomPath,spacing:item.spacing,hardness:item.hardness,scatter:item.scatter,rotation:item.rotation,pressureCurve:item.pressureCurve,speedCurve:item.speedCurve,flow:item.flow,wetness:item.wetness,grain:item.grain}},'Apply brush preset');global.LFStudio?.toast?.(`Brush preset “${item.name}” is active and remains recolorable.`)}
function open(){global.LFStudio?.togglePanel?.('presetCatalog',true);kind=$('#catalogKind')?.value||'shape';offset=0;load(kind)}
function bind(){
 $('#presetCatalogBtn')?.addEventListener('click',open);$('#objectPresetCatalog')?.addEventListener('click',open);
 $('#catalogKind')?.addEventListener('change',e=>{kind=e.target.value;offset=0;load(kind)});$('#catalogSearch')?.addEventListener('input',()=>{offset=0;render()});$('#catalogPrev')?.addEventListener('click',()=>{offset=Math.max(0,offset-PAGE);render()});$('#catalogNext')?.addEventListener('click',()=>{offset+=PAGE;render()});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();global.LFPresetCatalog={open,load,addShape,applyBrush};
})(window);