(function(){
'use strict';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const Studio={
 engine:null, projectType:'canvas-design', canvasBase:{kind:'transparent'}, pendingImport:false, toastTimer:null,
 init(){
  this.engine=new window.LFCanvasEngine($('#surfaceCanvas'),$('#overlayCanvas'),$('#canvasShell'));
  window.LFStudio=this;this.populateCanvasSizes();this.buildPalette();this.bindLauncher();window.SavanskiToolbarMenus?.bindStudioUI?.(this);this.bindWorkspaceControls();this.bindLayers();this.bindText();this.bindShortcuts();this.buildToolLibrary?.();this.bindEngine?.();this.refreshSaved();this.syncTheme();
  this.toast('Studio shell ready');
 },
 toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>el.classList.remove('show'),2600)},
 syncTheme(){const dark=document.documentElement.dataset.theme==='dark';$('#launcherTheme').classList.toggle('on',dark);},
 toggleTheme(){document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';this.syncTheme()},
 populateCanvasSizes(){const sel=$('#canvasSizeSelect');sel.innerHTML='';for(const cat of ['Canvas']){const g=document.createElement('optgroup');g.label=cat;for(const p of window.LFCanvasSizeRegistry.byCategory(cat)){const o=document.createElement('option');o.value=p.id;o.textContent=`${p.name} — ${p.label}`;if(p.id==='canvas-portrait-6x9')o.selected=true;g.appendChild(o)}sel.appendChild(g)}this.syncCanvasSizeDescription();sel.addEventListener('change',()=>this.syncCanvasSizeDescription())},
 syncCanvasSizeDescription(){const p=window.LFCanvasSizeRegistry.get($('#canvasSizeSelect').value);$('#canvasSizeDescription').textContent=p?`${p.category}: ${p.label}. ${p.use}. Canvas backing store: ${Math.round(p.widthIn*300).toLocaleString()} × ${Math.round(p.heightIn*300).toLocaleString()} px at 300 DPI.`:''},
 buildPalette(){const colors=['#000000','#ffffff','#787878','#b00020','#e51d37','#ff7a2e','#ffe500','#27a844','#1199d2','#3768bf','#8d43a3','#f3f3f3','#d0d0d0','#9b6951','#f28aa2','#ffc52e','#efe2a5','#a9e26a','#69cbd7','#739fd1','#b7a7d5'];const p=$('#palette');for(const c of colors){const b=document.createElement('button');b.className='swatch';b.style.setProperty('--c',c);b.title=c;b.addEventListener('click',()=>this.setPrimary(c));p.appendChild(b)}this.setPrimary('#000000');this.setSecondary('#ffffff')},
 setPrimary(c){this.engine.primary=c;$('#primaryColor').value=c;$('#primaryDot').style.setProperty('--c',c)},setSecondary(c){this.engine.secondary=c;$('#secondaryColor').value=c;$('#secondaryDot').style.setProperty('--c',c)},
 bindLauncher(){
  $$('#baseGrid .base-choice').forEach(b=>b.addEventListener('click',()=>{ $$('#baseGrid .base-choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');this.canvasBase={kind:b.dataset.kind};if(b.dataset.value)this.canvasBase.value=b.dataset.value;if(b.dataset.from){this.canvasBase.from=b.dataset.from;this.canvasBase.to=b.dataset.to}}));
  $$('[data-project-type]').forEach(b=>b.addEventListener('click',()=>{this.projectType=b.dataset.projectType;$$('[data-project-type]').forEach(x=>x.classList.toggle('selected',x===b));$('#canvasBaseSection').hidden=this.projectType==='canvas-set'}));
  $('#newProjectBtn').addEventListener('click',()=>this.createProject());$('#newProjectBtn2').addEventListener('click',()=>this.createProject());$('#importCard').addEventListener('click',()=>this.requestImport(true));$('#launcherTheme').addEventListener('click',()=>this.toggleTheme());window.addEventListener('savanski:home-request',()=>this.showLauncher());
 },
 async createProject(){try{const name=$('#launcherProjectName')?.value?.trim()||undefined;await this.engine.newProject({canvasSizeId:$('#canvasSizeSelect').value,projectType:this.projectType,canvasBase:this.canvasBase,dpi:300,name});this.openWorkspace();}catch(e){this.toast(e.message)}},
 openWorkspace(){const p=this.engine.project;if(!p)return;window.SavanskiSingleShell?.switchWorkspace?.('studio',{hideLauncher:false});$('#launcher').hidden=true;$('#emptyWorkspace').hidden=true;$('#canvasShell').hidden=false;$('#app').dataset.canvasSize=p.canvasSizeId;$('#workspace').classList.toggle('canvas-set',p.projectType==='canvas-set');this.updateStatus();this.renderLayers();this.updateCanvas();this.toast(`${p.projectType==='3d-object'?'3D Object':'Image / 1D'}: ${p.canvasSizeName}`)},
 showLauncher(){this.refreshSaved();$('#launcher').hidden=false},
 requestImport(fromLauncher=false){this.pendingImport=fromLauncher;$('#fileInput').click()},
 async handleImport(file){if(!file)return;try{if(/json$/i.test(file.name)||file.name.endsWith('.lfstudio')){const data=JSON.parse(await file.text());await this.engine.deserialize(data);this.openWorkspace();return}if(!this.engine.project){await this.engine.newProject({canvasSizeId:$('#canvasSizeSelect').value,projectType:this.projectType,canvasBase:this.canvasBase,dpi:300});this.openWorkspace()}await this.engine.importImage(file);this.toast(`Imported ${file.name}`)}catch(e){console.error(e);this.toast('Import failed: '+e.message)}},
 async refreshSaved(){try{const list=await window.LFStorage.list();$('#projectEmpty').hidden=list.length>0;$('#savedEmpty').hidden=list.length>0;const wrap=$('#savedProjects');wrap.innerHTML='';for(const p of list){const b=document.createElement('button');b.className='saved-row';const t=document.createElement('span');t.className='grow';const s=document.createElement('strong');s.textContent=p.name||'Untitled';const sm=document.createElement('small');sm.textContent=`${p.projectType==='3d-object'?'3D Object':'Image / 1D'} · ${p.canvasSizeName||p.canvasSizeId} · ${new Date(p.updatedAt||p.createdAt).toLocaleString()}`;t.append(s,document.createElement('br'),sm);b.append(t);const del=document.createElement('button');del.className='mini';del.textContent='×';del.title='Delete saved project';del.addEventListener('click',async e=>{e.stopPropagation();await LFStorage.remove(p.id);this.refreshSaved()});b.append(del);b.addEventListener('click',async()=>{const full=await LFStorage.get(p.id);await this.engine.deserialize(full);this.openWorkspace()});wrap.appendChild(b)}}catch(e){console.warn('Saved work unavailable',e)}},
 bindWorkspaceControls(){
  $('#launcherBtn').addEventListener('click',()=>this.showLauncher());$('#closeLayers').addEventListener('click',()=>this.toggleLayers(false));
  $('#zoomSlider').addEventListener('input',e=>this.engine.setZoom(+e.target.value/100));$('#zoomOut').addEventListener('click',()=>this.changeZoom(-.1));$('#zoomIn').addEventListener('click',()=>this.changeZoom(.1));
  $('#fileInput').addEventListener('change',e=>{this.handleImport(e.target.files[0]);e.target.value=''});$('#fontInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const name=await LFTextEngine.loadCustomFont(f);const o=document.createElement('option');o.value=o.textContent=name;$('#textFont').appendChild(o);$('#textFont').value=name;this.updateTextFromInspector();this.toast('Custom font loaded for this session')}catch(err){this.toast('Font could not be loaded')}e.target.value=''});
  $$('[data-close]').forEach(b=>b.addEventListener('click',()=>this.togglePanel(b.dataset.close,false)));
 },
 activateTool(id){if(!this.engine.project){this.showLauncher();return}const map={'free-select':'select'};this.engine.setTool(map[id]||id);$$('.ribbon-button[data-tool]').forEach(b=>b.classList.toggle('is-active',b.dataset.tool===id));},
 changeZoom(delta){const z=Math.max(.25,Math.min(2,this.engine.zoom+delta));$('#zoomSlider').value=Math.round(z*100);this.engine.setZoom(z)},
 togglePanel(id,force){const el=$('#'+id),open=force??!el.classList.contains('open');el.classList.toggle('open',open)},
 toggleLayers(force){$('#workspace').classList.toggle('layers-open',force??!$('#workspace').classList.contains('layers-open'))},
 async action(a){if(a==='new-launcher')return this.showLauncher();if(a==='import')return this.requestImport(false);if(a==='undo')return this.engine.history.undo();if(a==='redo')return this.engine.history.redo();if(a==='copy')return this.engine.copy();if(a==='cut')return this.engine.cut();if(a==='paste')return this.engine.paste();if(a==='fit')return this.engine.fit();if(a==='layers')return this.toggleLayers();if(a==='tool-library')return this.togglePanel('toolLibrary',true);if(window.LFToolRegistry.get(a))return window.LFToolRegistry.execute(a);},
 bindLayers(){
  $('#layerOpacity').addEventListener('input',e=>{const l=this.engine.activeLayer();if(l){l.opacity=+e.target.value/100;this.engine.render()}});$('#blendMode').addEventListener('change',e=>{const l=this.engine.activeLayer();if(l){l.blendMode=e.target.value;this.engine.render()}});
  const applyTransform=()=>{const l=this.engine.activeLayer();if(!l||l.locked)return;const sx=+$('#layerScaleX').value/100,sy=+$('#layerScaleY').value/100;l.transform.scaleX=Number.isFinite(sx)&&sx!==0?sx:.01;l.transform.scaleY=Number.isFinite(sy)&&sy!==0?sy:.01;l.transform.rotation=+$('#layerRotation').value||0;l.transform.x=+$('#layerX').value||0;l.transform.y=+$('#layerY').value||0;this.engine.render()};
  ['layerScaleX','layerScaleY','layerRotation','layerX','layerY'].forEach(id=>$('#'+id).addEventListener('change',applyTransform));
  $('#fitLayerBtn').addEventListener('click',()=>this.fitActiveLayer(false));$('#fillLayerBtn').addEventListener('click',()=>this.fitActiveLayer(true));$('#resetTransformBtn').addEventListener('click',()=>{const l=this.engine.activeLayer();if(!l||l.locked)return;const snap=this.engine.history.capture('Reset Transform');l.transform={x:0,y:0,rotation:0,scaleX:1,scaleY:1,skewX:0,skewY:0};this.engine.history.push(snap);this.engine.render();this.renderLayers()});
 },
 fitActiveLayer(cover=false){const e=this.engine,l=e.activeLayer();if(!l||l.locked)return;const bounds=this.layerPixelBounds(l);if(!bounds.w||!bounds.h)return this.toast('This layer has no visible content to fit.');const snap=e.history.capture(cover?'Fill Layer':'Fit Layer'),scale=cover?Math.max(e.width/bounds.w,e.height/bounds.h):Math.min(e.width/bounds.w,e.height/bounds.h);l.transform.scaleX=(l.transform.scaleX<0?-1:1)*scale;l.transform.scaleY=(l.transform.scaleY<0?-1:1)*scale;l.transform.x=(e.width/2-(bounds.x+bounds.w/2))*scale;l.transform.y=(e.height/2-(bounds.y+bounds.h/2))*scale;e.history.push(snap);e.render();this.renderLayers();this.toast(cover?'Layer fills canvas':'Layer fit to canvas')},
 layerPixelBounds(l){const c=l.canvas,ctx=c.getContext('2d',{willReadFrequently:true});try{const d=ctx.getImageData(0,0,c.width,c.height).data;let minX=c.width,minY=c.height,maxX=-1,maxY=-1;const step=Math.max(1,Math.floor(Math.max(c.width,c.height)/1800));for(let y=0;y<c.height;y+=step){for(let x=0;x<c.width;x+=step){if(d[(y*c.width+x)*4+3]>3){if(x<minX)minX=x;if(y<minY)minY=y;if(x>maxX)maxX=x;if(y>maxY)maxY=y}}}if(maxX<0)return{x:0,y:0,w:0,h:0};return{x:minX,y:minY,w:Math.max(step,maxX-minX+step),h:Math.max(step,maxY-minY+step)}}catch{return{x:0,y:0,w:c.width,h:c.height}}},
 renderLayers(){const ul=$('#layerList');ul.innerHTML='';const p=this.engine.canvas();if(!p)return;[...p.layers].reverse().forEach(l=>{const li=document.createElement('li');li.className='layer-row'+(l.id===this.engine.activeLayerId?' active':'');li.addEventListener('click',()=>this.engine.selectLayer(l.id));const vis=document.createElement('button');vis.className='mini';vis.textContent=l.visible?'◉':'○';vis.title=l.visible?'Hide layer':'Show layer';vis.addEventListener('click',e=>{e.stopPropagation();l.visible=!l.visible;this.engine.render();this.renderLayers()});const name=document.createElement('span');name.className='layer-name';name.textContent=(l.locked?'🔒 ':'')+l.name;const acts=document.createElement('span');acts.className='layer-actions';const up=document.createElement('button');up.className='mini';up.textContent='↑';up.addEventListener('click',e=>{e.stopPropagation();this.engine.selectLayer(l.id);this.engine.moveLayerOrder(1)});const down=document.createElement('button');down.className='mini';down.textContent='↓';down.addEventListener('click',e=>{e.stopPropagation();this.engine.selectLayer(l.id);this.engine.moveLayerOrder(-1)});acts.append(up,down);li.append(vis,name,acts);ul.appendChild(li)});const l=this.engine.activeLayer();if(l){$('#layerOpacity').value=Math.round(l.opacity*100);$('#blendMode').value=l.blendMode||'source-over';$('#layerScaleX').value=Math.round((l.transform?.scaleX??1)*10000)/100;$('#layerScaleY').value=Math.round((l.transform?.scaleY??1)*10000)/100;$('#layerRotation').value=Math.round((l.transform?.rotation||0)*100)/100;$('#layerX').value=Math.round((l.transform?.x||0)*100)/100;$('#layerY').value=Math.round((l.transform?.y||0)*100)/100}},
 bindShortcuts(){window.addEventListener('keydown',e=>{if(document.body.dataset.workspace==='3d')return;const typing=/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName||'');if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?this.action('redo'):this.action('undo');return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();this.action('redo');return}if(typing)return;if(e.key==='Escape'){document.querySelectorAll('.floating-panel.open').forEach(x=>x.classList.remove('open'));return}})},
 bindText(){
  const ids=['textValue','textFont','textSize','textColor','textOpacity','strokeColor','strokeWidth','letterSpacing','lineHeight','bendRadius','bendEnabled','textDepth','depthColor','textSkew','textRotateY','shadowEnabled','shadowColor','shadowBlur','shadowX','shadowY','gradientEnabled','gradientFrom','gradientTo','gradientAngle'];ids.forEach(id=>$('#'+id).addEventListener(id==='textValue'?'input':'change',()=>this.updateTextFromInspector()));
  $$('[data-text-toggle]').forEach(b=>b.addEventListener('click',()=>{const l=this.engine.activeLayer();if(!l||l.type!=='text')return;const k=b.dataset.textToggle;l.meta[k]=!l.meta[k];b.classList.toggle('selected',l.meta[k]);LFTextEngine.render(this.engine,l)}));
  $('#loadFontBtn').addEventListener('click',()=>$('#fontInput').click());$('#textTextureBtn').addEventListener('click',()=>{const l=this.engine.activeLayer();if(!l||l.type!=='text')return this.toast('Select a text layer first.');$('#textTextureInput').click()});$('#clearTextTextureBtn').addEventListener('click',()=>{const l=this.engine.activeLayer();if(!l||l.type!=='text')return;l.meta.textureData=null;LFTextEngine.render(this.engine,l);this.toast('Text texture cleared')});$('#textTextureInput').addEventListener('change',async e=>{const f=e.target.files[0],l=this.engine.activeLayer();if(!f||!l||l.type!=='text')return;try{l.meta.textureData=await LFTextEngine.textureFromFile(f);LFTextEngine.render(this.engine,l);this.toast('User texture applied inside text')}catch{this.toast('Texture could not be loaded')}e.target.value=''});$('#applySegment').addEventListener('click',()=>{const box=$('#textValue'),l=this.engine.activeLayer();if(!l||l.type!=='text'||box.selectionStart===box.selectionEnd)return this.toast('Select part of the text first.');LFTextEngine.applyRun(this.engine,box.selectionStart,box.selectionEnd,{color:$('#segmentColor').value,opacity:+$('#segmentOpacity').value/100,highlight:$('#segmentHighlight').value});this.toast('Segment style applied')});$('#clearSegments').addEventListener('click',()=>LFTextEngine.clearRuns(this.engine));
 },
 updateTextFromInspector(){const l=this.engine.activeLayer();if(!l||l.type!=='text')return;const m=l.meta;m.text=$('#textValue').value;m.fontFamily=$('#textFont').value;m.fontSize=+$('#textSize').value;m.color=$('#textColor').value;m.opacity=+$('#textOpacity').value/100;m.strokeColor=$('#strokeColor').value;m.strokeWidth=+$('#strokeWidth').value;m.letterSpacing=+$('#letterSpacing').value;m.lineHeight=+$('#lineHeight').value;m.bend=$('#bendEnabled').checked;m.bendRadius=+$('#bendRadius').value;m.depth=+$('#textDepth').value;m.depthColor=$('#depthColor').value;m.skewX=+$('#textSkew').value;m.rotateY=+$('#textRotateY').value;m.shadow={...m.shadow,enabled:$('#shadowEnabled').checked,color:$('#shadowColor').value,blur:+$('#shadowBlur').value,x:+$('#shadowX').value,y:+$('#shadowY').value};m.gradient={...m.gradient,enabled:$('#gradientEnabled').checked,from:$('#gradientFrom').value,to:$('#gradientTo').value,angle:+$('#gradientAngle').value};LFTextEngine.render(this.engine,l)},
 syncTextInspector(l=this.engine.activeLayer()){if(!l||l.type!=='text')return;const m=l.meta;$('#textValue').value=m.text;$('#textFont').value=m.fontFamily;$('#textSize').value=m.fontSize;$('#textColor').value=m.color;$('#textOpacity').value=Math.round(m.opacity*100);$('#strokeColor').value=m.strokeColor;$('#strokeWidth').value=m.strokeWidth;$('#letterSpacing').value=m.letterSpacing;$('#lineHeight').value=m.lineHeight;$('#bendEnabled').checked=m.bend;$('#bendRadius').value=m.bendRadius;$('#textDepth').value=m.depth;$('#depthColor').value=m.depthColor;$('#textSkew').value=m.skewX;$('#textRotateY').value=m.rotateY;$('#shadowEnabled').checked=m.shadow.enabled;$('#shadowColor').value=m.shadow.color;$('#shadowBlur').value=m.shadow.blur;$('#shadowX').value=m.shadow.x;$('#shadowY').value=m.shadow.y;$('#gradientEnabled').checked=m.gradient.enabled;$('#gradientFrom').value=m.gradient.from;$('#gradientTo').value=m.gradient.to;$('#gradientAngle').value=m.gradient.angle;$$('[data-text-toggle]').forEach(b=>b.classList.toggle('selected',!!m[b.dataset.textToggle]))},

 executeUI(id,args){if(id.startsWith('text-')||id==='text-inspector'){const l=this.engine.activeLayer();if(!l||l.type!=='text'){LFTextEngine.insertAt(this.engine,this.engine.width/2,this.engine.height/2);this.syncTextInspector()}else this.syncTextInspector(l);this.togglePanel('textInspector',true);return}if(id==='custom-font')return $('#fontInput').click();if(id==='overlay-image')return this.requestImport(false);if(id==='shape-library'){this.togglePanel('toolLibrary',true);$('#toolSearch').value='shape';$('#toolSearch').dispatchEvent(new Event('input'));return}if(['blend-mode','opacity','scale-layer'].includes(id)){this.toggleLayers(true);return}if(id==='fit-layer'){this.toggleLayers(true);return this.fitActiveLayer(false)}if(id==='fill-layer'){this.toggleLayers(true);return this.fitActiveLayer(true)}},
 async executeLocalAction(id,args){const e=this.engine;switch(id){
   case'save':if(!e.project)return;$('#statusSave').textContent='Saving…';{const data=await e.saveLocal();let msg='Project saved locally';if(window.SavanskiOurSpaceBackend?.canSync?.()){try{await window.SavanskiOurSpaceBackend.saveProject(data);msg='Project saved locally + synced to Savanski';window.SavanskiOurSpaceGame?.post?.('ourspace:game-saved',{projectId:data.id||'',projectName:data.name||''});}catch(err){console.warn(err);msg='Project saved locally; Savanski sync skipped: '+err.message}}this.toast(msg)}break;
   case'export-project':if(e.project)await LFExport.project(e);break;case'export-png':await LFExport.image(e,'png');break;case'export-jpg':await LFExport.image(e,'jpg');break;case'export-webp':await LFExport.image(e,'webp');break;
   case'select-all':e.selectAll();break;case'deselect':e.clearSelection();break;case'rotate-left':e.rotateLayer(-90);break;case'rotate-right':e.rotateLayer(90);break;case'flip-horizontal':e.flipLayer('x');break;case'flip-vertical':e.flipLayer('y');break;case'center-layer':e.centerLayer();break;
   case'add-layer':e.addLayer();break;case'duplicate-layer':e.duplicateLayer();break;case'delete-layer':e.deleteLayer();break;case'layer-up':e.moveLayerOrder(1);break;case'layer-down':e.moveLayerOrder(-1);break;case'merge-down':e.mergeDown();break;case'layer-mask':e.addMask();break;case'remove-mask':e.removeMask();break;
   case'guides':e.guides=!e.guides;e.renderOverlay();this.toast(`Print guides ${e.guides?'on':'off'}`);break;case'snap-grid':e.snap=!e.snap;e.guides=e.snap||e.guides;e.renderOverlay();this.toast(`Snapping ${e.snap?'on':'off'}; guides never export`);break;case'pin-background':{const l=e.canvas().layers.find(x=>x.name==='Canvas Base');if(l){l.locked=!l.locked;this.renderLayers();this.toast(l.locked?'Canvas Base pinned':'Canvas Base unpinned')}break}
   case'background-remove-local':LFImageTools.removeSolidBackground(e,+args.tolerance||34);break;
   case'auto-levels':LFImageTools.autoLevels(e);break;case'grain':LFImageTools.grain(e,+args.amount||.08);break;case'pixelate':LFImageTools.pixelate(e,+args.size||12);break;case'vignette':LFImageTools.vignette(e,+args.strength||.45);break;case'duotone':{const c1=args.from||window.prompt('Duotone shadow color','#1c1c6b'),c2=args.to||window.prompt('Duotone highlight color','#ffbd59');if(c1&&c2)LFImageTools.duotone(e,c1,c2);break}
   case'brightness':case'contrast':case'saturation':{let def=id==='brightness'?1.1:id==='contrast'?1.12:1.12;let v=args.value||window.prompt(`${id}: multiplier (1 = unchanged)`,String(def));if(v)LFImageTools.applyFilter(e,id,+v);break}case'hue':{let v=args.value||window.prompt('Hue rotation in degrees','15');if(v!=null)LFImageTools.applyFilter(e,'hue',+v);break}case'blur':{let v=args.value||window.prompt('Blur radius in pixels','3');if(v)LFImageTools.applyFilter(e,'blur',+v);break}
   case'grayscale':case'sepia':case'invert':case'sharpen':case'unblur':case'clarity':case'dehaze':case'auto-enhance':case'vintage':case'cool':case'warm':case'noir':case'fade':LFImageTools.applyFilter(e,id,args.value);break;
   case'emoji-sticker':{const s=args.text||window.prompt('Emoji or symbol to insert','★');if(s){const l=LFTextEngine.insertAt(e,e.width/2,e.height/2,s);l.meta.fontSize=100;LFTextEngine.render(e,l);this.syncTextInspector(l)}break}
   case'text-behind':e.moveLayerOrder(-1);this.toast('Moved the active layer backward. Use eraser/background removal on the foreground layer for a text-behind effect.');break;
   case'canvas-layout':this.createCanvasLayout();break;case'collage':this.collage();break;
   case'canvas-add':e.addCanvas();break;case'canvas-duplicate':e.duplicateCanvas();break;case'canvas-delete':e.deleteCanvas();break;case'canvas-prev':e.goCanvas(-1);break;case'canvas-next':e.goCanvas(1);break;case'export-canvases':await LFExport.canvasSet(e);break;
   default:console.warn('Unhandled local action',id);this.toast(`${id.replace(/-/g,' ')} is available in the shell.`);break;
  }},
 createCanvasLayout(){const e=this.engine,s=e.history.capture('Canvas Layout');const title=LFTextEngine.insertAt(e,e.width/2,e.height*.22,'CANVAS TITLE');title.meta.fontFamily='Georgia';title.meta.fontSize=72;title.meta.bold=true;title.meta.boxWidth=e.project.widthIn*60;LFTextEngine.render(e,title);const sub=LFTextEngine.insertAt(e,e.width/2,e.height*.34,'A compelling subtitle');sub.meta.fontSize=26;LFTextEngine.render(e,sub);const creator=LFTextEngine.insertAt(e,e.width/2,e.height*.86,'CREATOR NAME');creator.meta.fontSize=30;creator.meta.letterSpacing=2;LFTextEngine.render(e,creator);e.history.push(s);e.render();this.toast('Editable art typography added')},
 collage(){const e=this.engine,layers=e.canvas().layers.filter(l=>l.visible&&!l.locked&&l.name!=='Canvas Base');if(layers.length<2)return this.toast('Import at least two image layers first.');const snap=e.history.capture('Collage');const n=layers.length,cols=Math.ceil(Math.sqrt(n)),rows=Math.ceil(n/cols);layers.forEach((l,i)=>{const col=i%cols,row=Math.floor(i/cols);l.transform.scaleX=l.transform.scaleY=Math.min(.92/cols,.92/rows);l.transform.x=((col+.5)/cols-.5)*e.width;l.transform.y=((row+.5)/rows-.5)*e.height});e.history.push(snap);e.render();this.toast('Visible layers arranged as a collage')}
};
document.addEventListener('DOMContentLoaded',()=>Studio.init());
})();
