(function(){
'use strict';
const S=window.Savanski,st=S.state;
const O=()=>S.$('#interactionCanvas');
const colorDistance=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2],(a[3]-b[3])*.3);
function hexRGB(hex){hex=String(hex||'#000000').replace('#','');if(hex.length===3)hex=hex.split('').map(x=>x+x).join('');return[parseInt(hex.slice(0,2),16)||0,parseInt(hex.slice(2,4),16)||0,parseInt(hex.slice(4,6),16)||0,255]}
function settings(){return{size:+S.$('#brushSize').value||18,opacity:(+S.$('#brushOpacity').value||100)/100,soft:(+S.$('#brushSoftness').value||0)/100,color:S.$('#primaryColor').value}}
function activeOK(){const l=S.activeLayer();if(!l){S.toast('Add a layer first.','error');return null}if(l.locked){S.toast('The active layer is locked.','error');return null}return l}
function setupBrush(ctx,tool){const a=settings();ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=a.size;ctx.strokeStyle=a.color;ctx.fillStyle=a.color;ctx.globalAlpha=a.opacity;ctx.globalCompositeOperation=tool==='eraser'||tool==='fogReveal'?'destination-out':'source-over';ctx.shadowBlur=0;ctx.shadowColor='transparent';if(tool==='marker'){ctx.globalAlpha*=.48;ctx.lineWidth=a.size*1.25}if(tool==='crayon'){ctx.globalAlpha*=.72;ctx.lineWidth=a.size*.75}if(tool==='neon'){ctx.shadowColor=a.color;ctx.shadowBlur=Math.max(8,a.size*1.3);ctx.lineWidth=Math.max(2,a.size*.42)}if(tool==='pencil')ctx.lineWidth=Math.max(1,a.size*.35);return a}
function drawDot(l,p,tool){const ctx=l.ctx,a=setupBrush(ctx,tool);ctx.save();if(tool==='airbrush'){const count=Math.max(8,Math.round(a.size*.8));ctx.globalAlpha=a.opacity*.16;for(let i=0;i<count;i++){const r=Math.random()*a.size*.6,ang=Math.random()*Math.PI*2,rr=Math.random()*Math.max(1,a.size*.08);ctx.beginPath();ctx.arc(p.x+Math.cos(ang)*r,p.y+Math.sin(ang)*r,rr,0,Math.PI*2);ctx.fill()}}else if(tool==='crayon'){for(let i=0;i<5;i++){ctx.globalAlpha=a.opacity*(.12+Math.random()*.15);ctx.beginPath();ctx.arc(p.x+(Math.random()-.5)*a.size*.6,p.y+(Math.random()-.5)*a.size*.6,Math.max(1,a.size*(.08+Math.random()*.12)),0,Math.PI*2);ctx.fill()}}else{ctx.beginPath();ctx.arc(p.x,p.y,Math.max(1,ctx.lineWidth/2),0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawSegment(l,a,b,tool){const ctx=l.ctx,s=setupBrush(ctx,tool);ctx.save();if(tool==='airbrush'){const dist=Math.hypot(b.x-a.x,b.y-a.y),steps=Math.max(1,Math.ceil(dist/Math.max(2,s.size*.1)));for(let i=0;i<=steps;i++){const t=i/steps;drawDot(l,{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t},tool)}ctx.restore();return}if(tool==='crayon'){for(let i=0;i<4;i++){ctx.globalAlpha=s.opacity*(.12+Math.random()*.12);ctx.beginPath();ctx.moveTo(a.x+(Math.random()-.5)*s.size*.35,a.y+(Math.random()-.5)*s.size*.35);ctx.lineTo(b.x+(Math.random()-.5)*s.size*.35,b.y+(Math.random()-.5)*s.size*.35);ctx.stroke()}ctx.restore();return}ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore()}
function shapeSettings(){return{fill:S.$('#shapeFill').value,stroke:S.$('#shapeStroke').value,sw:+S.$('#shapeStrokeWidth').value||0,fillAlpha:(+S.$('#shapeFillOpacity').value||0)/100,useFill:S.$('#shapeFillEnabled').checked,useStroke:S.$('#shapeStrokeEnabled').checked}}
function pathShape(ctx,tool,a,b){let x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.abs(b.x-a.x),h=Math.abs(b.y-a.y);ctx.beginPath();if(tool==='rect')ctx.rect(x,y,w,h);else if(tool==='ellipse'){ctx.ellipse(x+w/2,y+h/2,w/2,h/2,0,0,Math.PI*2)}else if(tool==='triangle'){ctx.moveTo(x+w/2,y);ctx.lineTo(x+w,y+h);ctx.lineTo(x,y+h);ctx.closePath()}else if(tool==='star'){const cx=x+w/2,cy=y+h/2,outer=Math.min(w,h)/2,inner=outer*.45;for(let i=0;i<10;i++){const r=i%2?inner:outer,ang=-Math.PI/2+i*Math.PI/5,px=cx+Math.cos(ang)*r,py=cy+Math.sin(ang)*r;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath()}else if(tool==='line'||tool==='arrow'){ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);if(tool==='arrow'){const ang=Math.atan2(b.y-a.y,b.x-a.x),len=Math.max(12,Math.min(60,Math.hypot(b.x-a.x,b.y-a.y)*.16));ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-Math.cos(ang-.55)*len,b.y-Math.sin(ang-.55)*len);ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-Math.cos(ang+.55)*len,b.y-Math.sin(ang+.55)*len)}}}
function paintShape(ctx,tool,a,b){const s=shapeSettings();ctx.save();ctx.lineJoin='round';pathShape(ctx,tool,a,b);if(!['line','arrow'].includes(tool)&&s.useFill){ctx.globalAlpha=s.fillAlpha;ctx.fillStyle=s.fill;ctx.fill()}if(s.useStroke||['line','arrow'].includes(tool)){ctx.globalAlpha=1;ctx.strokeStyle=s.stroke;ctx.lineWidth=Math.max(1,s.sw);ctx.stroke()}ctx.restore()}
function clearOverlay(){const c=O();c.getContext('2d').clearRect(0,0,c.width,c.height)}
function previewShape(tool,a,b){clearOverlay();const c=O(),ctx=c.getContext('2d');paintShape(ctx,tool,a,b)}
function selectionPath(ctx,sel,offsetX=0,offsetY=0){if(!sel)return;let{x0,y0,x1,y1}=sel;x0-=offsetX;y0-=offsetY;x1-=offsetX;y1-=offsetY;let x=Math.min(x0,x1),y=Math.min(y0,y1),w=Math.abs(x1-x0),h=Math.abs(y1-y0);ctx.beginPath();const shape=sel.shape||'rect';if(shape==='rect'||shape==='square')ctx.rect(x,y,w,h);else if(shape==='ellipse'||shape==='circle')ctx.ellipse(x+w/2,y+h/2,w/2,h/2,0,0,Math.PI*2);else if(shape==='triangle'){ctx.moveTo(x+w/2,y);ctx.lineTo(x+w,y+h);ctx.lineTo(x,y+h);ctx.closePath()}else if(shape==='free'&&sel.points?.length){ctx.moveTo(sel.points[0].x-offsetX,sel.points[0].y-offsetY);for(const p of sel.points.slice(1))ctx.lineTo(p.x-offsetX,p.y-offsetY);ctx.closePath()}else ctx.rect(x,y,w,h)}
function normalizeSelection(sel){if(!sel)return sel;if(['square','circle'].includes(sel.shape)){const dx=sel.x1-sel.x0,dy=sel.y1-sel.y0,size=Math.max(Math.abs(dx),Math.abs(dy));sel.x1=sel.x0+(dx<0?-size:size);sel.y1=sel.y0+(dy<0?-size:size)}return sel}
S.renderSelectionOverlay=function(){const c=O();if(!c)return;const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);const sel=st.selection;if(!sel)return;ctx.save();ctx.setLineDash([8,5]);ctx.lineWidth=Math.max(1,2/st.zoom);ctx.strokeStyle='#001010';ctx.shadowColor='#F2FFFF';ctx.shadowBlur=2;selectionPath(ctx,sel);ctx.stroke();ctx.restore()};
function selectionBounds(sel){normalizeSelection(sel);if(sel.shape==='free'&&sel.points?.length){const xs=sel.points.map(p=>p.x),ys=sel.points.map(p=>p.y);return{x:Math.floor(Math.min(...xs)),y:Math.floor(Math.min(...ys)),w:Math.max(1,Math.ceil(Math.max(...xs)-Math.min(...xs))),h:Math.max(1,Math.ceil(Math.max(...ys)-Math.min(...ys)))}}return{x:Math.floor(Math.min(sel.x0,sel.x1)),y:Math.floor(Math.min(sel.y0,sel.y1)),w:Math.max(1,Math.ceil(Math.abs(sel.x1-sel.x0))),h:Math.max(1,Math.ceil(Math.abs(sel.y1-sel.y0)))}}
S.copySelection=async function(cut=false){const l=activeOK(),sel=st.selection;if(!l||!sel){S.toast('Make a selection first.','error');return}const b=selectionBounds(sel),c=document.createElement('canvas');c.width=b.w;c.height=b.h;const ctx=c.getContext('2d');ctx.save();selectionPath(ctx,sel,b.x,b.y);ctx.clip();ctx.drawImage(l.canvas,-b.x,-b.y);ctx.restore();st.clipboard={canvas:c,w:b.w,h:b.h};try{if(navigator.clipboard?.write&&window.ClipboardItem){const blob=await S.canvasBlob(c);await navigator.clipboard.write([new ClipboardItem({'image/png':blob})])}}catch(e){console.debug('OS clipboard unavailable',e)}if(cut){S.snapshot('Cut selection');l.ctx.save();selectionPath(l.ctx,sel);l.ctx.clip();l.ctx.clearRect(0,0,l.canvas.width,l.canvas.height);l.ctx.restore();S.renderLayers();S.autosave?.()}S.toast(cut?'Cut selection':'Copied selection','success')};
S.pasteClipboard=async function(){let c=st.clipboard?.canvas||null;if(!c&&navigator.clipboard?.read){try{for(const item of await navigator.clipboard.read()){const type=item.types.find(t=>t.startsWith('image/'));if(type){const blob=await item.getType(type),url=URL.createObjectURL(blob);const im=await S.loadImage(url);const cc=document.createElement('canvas');cc.width=im.naturalWidth;cc.height=im.naturalHeight;cc.getContext('2d').drawImage(im,0,0);URL.revokeObjectURL(url);c=cc;break}}}catch(e){console.debug(e)}}if(!c){S.toast('No image is available to paste.','error');return}const l=S.newLayer('Pasted image');const x=(st.project.width-c.width)/2,y=(st.project.height-c.height)/2;l.ctx.drawImage(c,x,y);S.renderLayers();S.toast('Pasted on a new layer','success')};
S.cropSelection=function(){const sel=st.selection;if(!sel){S.toast('Make a selection first.','error');return}const p=st.project,b=selectionBounds(sel);if(b.w<2||b.h<2)return;for(const l of p.layers){const n=document.createElement('canvas');n.width=b.w;n.height=b.h;const c=n.getContext('2d',{willReadFrequently:true});c.save();selectionPath(c,sel,b.x,b.y);c.clip();c.drawImage(l.canvas,-b.x,-b.y);c.restore();l.canvas=n;l.ctx=c}p.width=b.w;p.height=b.h;st.selection=null;S.resizeViewCanvases();S.renderLayers();S.renderLayerList();S.syncProjectUI?.();S.autosave?.();S.toast(`Cropped to ${b.w} × ${b.h}`,'success')};
function floodFill(l,x,y,color,tol){const w=l.canvas.width,h=l.canvas.height,x0=Math.floor(x),y0=Math.floor(y);const img=l.ctx.getImageData(0,0,w,h),d=img.data,idx=(y0*w+x0)*4,target=[d[idx],d[idx+1],d[idx+2],d[idx+3]],fill=hexRGB(color);if(colorDistance(target,fill)<2)return;const limit=tol*4.42,seen=new Uint8Array(w*h),stack=[x0,y0];while(stack.length){const cy=stack.pop(),cx=stack.pop();if(cx<0||cy<0||cx>=w||cy>=h)continue;const pos=cy*w+cx;if(seen[pos])continue;seen[pos]=1;const i=pos*4;if(colorDistance([d[i],d[i+1],d[i+2],d[i+3]],target)>limit)continue;d[i]=fill[0];d[i+1]=fill[1];d[i+2]=fill[2];d[i+3]=255;stack.push(cx+1,cy,cx-1,cy,cx,cy+1,cx,cy-1)}l.ctx.putImageData(img,0,0)}
function colorErase(l,x,y){const w=l.canvas.width,h=l.canvas.height,img=l.ctx.getImageData(0,0,w,h),d=img.data,clicked=(Math.floor(y)*w+Math.floor(x))*4;const chosen=S.$('#removeColor').value,target=S.$('#removeContiguous').checked?[d[clicked],d[clicked+1],d[clicked+2],d[clicked+3]]:hexRGB(chosen),tol=(+S.$('#removeTolerance').value||0)*4.42,str=(+S.$('#removeStrength').value||100)/100,contig=S.$('#removeContiguous').checked;if(contig){const seen=new Uint8Array(w*h),stack=[Math.floor(x),Math.floor(y)];while(stack.length){const cy=stack.pop(),cx=stack.pop();if(cx<0||cy<0||cx>=w||cy>=h)continue;const pos=cy*w+cx;if(seen[pos])continue;seen[pos]=1;const i=pos*4;if(colorDistance([d[i],d[i+1],d[i+2],d[i+3]],target)>tol)continue;d[i+3]=Math.max(0,Math.round(d[i+3]*(1-str)));stack.push(cx+1,cy,cx-1,cy,cx,cy+1,cx,cy-1)}}else{for(let i=0;i<d.length;i+=4)if(colorDistance([d[i],d[i+1],d[i+2],d[i+3]],target)<=tol)d[i+3]=Math.max(0,Math.round(d[i+3]*(1-str)))}l.ctx.putImageData(img,0,0)}
S.removeColorGlobal=function(){const l=activeOK();if(!l)return;S.snapshot('Remove color');const old=S.$('#removeContiguous').checked;S.$('#removeContiguous').checked=false;colorErase(l,0,0);S.$('#removeContiguous').checked=old;S.renderLayers();S.autosave?.();S.toast('Color removal applied','success')};
function pickColor(p){const c=S.compositeCanvas({grid:false}),d=c.getContext('2d').getImageData(Math.floor(p.x),Math.floor(p.y),1,1).data;const hex='#'+[d[0],d[1],d[2]].map(x=>x.toString(16).padStart(2,'0')).join('');S.$('#primaryColor').value=hex;S.$('#removeColor').value=hex;S.toast(`Picked ${hex}`)}
function drawTextAt(x,y){const l=activeOK();if(!l)return;const text=S.$('#textValue').value||'Text',size=+S.$('#textSize').value||72,font=S.$('#textFont').value||'Arial',bold=S.$('#textBold').classList.contains('active'),italic=S.$('#textItalic').classList.contains('active'),rot=(+S.$('#textRotation').value||0)*Math.PI/180,fill=S.$('#textFill').value,stroke=S.$('#textStroke').value,sw=+S.$('#textStrokeWidth').value||0,shadow=+S.$('#textShadow').value||0,useBg=S.$('#textUseBackground').checked,bg=S.$('#textBackground').value,curved=S.$('#textCurved').checked,curve=(+S.$('#textCurve').value||0)*Math.PI/180;S.snapshot('Add text');const ctx=l.ctx;ctx.save();ctx.translate(x,y);ctx.rotate(rot);ctx.font=`${italic?'italic ':''}${bold?'bold ':''}${size}px ${font}`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineJoin='round';ctx.shadowColor='rgba(0,0,0,.7)';ctx.shadowBlur=shadow;ctx.shadowOffsetX=shadow*.3;ctx.shadowOffsetY=shadow*.3;if(useBg){const metrics=ctx.measureText(text),pad=size*.18;ctx.shadowBlur=0;ctx.fillStyle=bg;ctx.globalAlpha=.9;ctx.fillRect(-metrics.width/2-pad,-size*.65,metrics.width+pad*2,size*1.3);ctx.globalAlpha=1;ctx.shadowBlur=shadow}ctx.fillStyle=fill;ctx.strokeStyle=stroke;ctx.lineWidth=sw;if(curved&&text.length>1){const chars=[...text],radius=Math.max(size*1.4,chars.length*size*.42/Math.max(.05,Math.abs(curve))),start=-curve/2;chars.forEach((ch,i)=>{const a=start+curve*(i/(chars.length-1));ctx.save();ctx.rotate(a);ctx.translate(0,-radius);ctx.rotate(-a);if(sw)ctx.strokeText(ch,0,0);ctx.fillText(ch,0,0);ctx.restore()})}else{for(const [i,line] of text.split(/\n/).entries()){const yy=(i-(text.split(/\n/).length-1)/2)*size*1.15;if(sw)ctx.strokeText(line,0,yy);ctx.fillText(line,0,yy)}}ctx.restore();S.renderLayers();S.autosave?.()}
S.addTextAt=drawTextAt;
function rulerPreview(a,b,commit=false){clearOverlay();const ctx=O().getContext('2d'),dist=Math.hypot(b.x-a.x,b.y-a.y),cells=dist/(st.map.gridSize||70),value=cells*(st.map.units||5);ctx.save();ctx.strokeStyle='#FFF600';ctx.fillStyle='#001010';ctx.lineWidth=Math.max(2,3/st.zoom);ctx.setLineDash([7,5]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);ctx.font=`${Math.max(13,16/st.zoom)}px Arial`;const label=`${value.toFixed(value<10?1:0)} ${st.map.unitName||'ft'}`,mx=(a.x+b.x)/2,my=(a.y+b.y)/2,w=ctx.measureText(label).width+10;ctx.fillStyle='#FFF600';ctx.fillRect(mx-w/2,my-22,w,22);ctx.strokeStyle='#001010';ctx.strokeRect(mx-w/2,my-22,w,22);ctx.fillStyle='#001010';ctx.textAlign='center';ctx.fillText(label,mx,my-6);ctx.restore();if(commit)S.status(`Measured ${label}`)}
function lightAt(p){let l=st.project.layers.find(x=>x.kind==='lighting');if(!l){l=S.newLayer('Lighting',{kind:'lighting'});l.blend='screen';l.opacity=.95}S.setActiveLayer(l.id);S.snapshot('Place light');const c=l.ctx,r=Math.max(40,+S.$('#brushSize').value*5),col=S.$('#primaryColor').value,g=c.createRadialGradient(p.x,p.y,0,p.x,p.y,r);g.addColorStop(0,col+'ff');g.addColorStop(.18,col+'bb');g.addColorStop(.6,col+'44');g.addColorStop(1,col+'00');c.save();c.globalCompositeOperation='lighter';c.fillStyle=g;c.beginPath();c.arc(p.x,p.y,r,0,Math.PI*2);c.fill();c.restore();S.renderLayers();S.autosave?.()}
function fogLayer(){let l=st.project.layers.find(x=>x.kind==='fog');if(!l){l=S.newLayer('Fog of War',{kind:'fog'});l.opacity=.82;l.ctx.fillStyle='#001010';l.ctx.fillRect(0,0,l.canvas.width,l.canvas.height);S.renderLayers();S.renderLayerList()}return l}
S.ensureFogLayer=fogLayer;
function pointerDown(e){if(e.button!==0)return;const p=S.pointerToCanvas(e);st.pointer={start:p,last:p,current:p};const tool=st.tool,l=activeOK();if(['pencil','brush','marker','crayon','airbrush','neon','eraser'].includes(tool)){if(!l)return;S.snapshot(`Draw ${tool}`);st.isDrawing=true;drawDot(l,p,tool);S.renderLayers();O().setPointerCapture?.(e.pointerId);e.preventDefault();return}if(tool==='fogReveal'){const fog=fogLayer();S.setActiveLayer(fog.id);S.snapshot('Reveal fog');st.isDrawing=true;drawDot(fog,p,'fogReveal');S.renderLayers();O().setPointerCapture?.(e.pointerId);return}if(tool==='fill'){if(!l)return;S.snapshot('Fill');floodFill(l,p.x,p.y,S.$('#primaryColor').value,+S.$('#removeTolerance').value||18);S.renderLayers();S.autosave?.();return}if(tool==='magicErase'){if(!l)return;S.snapshot('Connected color erase');colorErase(l,p.x,p.y);S.renderLayers();S.autosave?.();return}if(tool==='eyedropper'){pickColor(p);return}if(tool==='text'){drawTextAt(p.x,p.y);return}if(tool==='light'){lightAt(p);return}if(tool==='lasso'){st.selection={shape:'free',x0:p.x,y0:p.y,x1:p.x,y1:p.y,points:[p]};st.isDrawing=true;return}if(tool==='select'){st.selection={shape:S.$('#selectionShape').value,x0:p.x,y0:p.y,x1:p.x,y1:p.y,points:[]};st.isDrawing=true;S.renderSelectionOverlay();return}if(['line','arrow','rect','ellipse','triangle','star','ruler'].includes(tool)){st.isDrawing=true;O().setPointerCapture?.(e.pointerId);return}}
function pointerMove(e){const p=S.pointerToCanvas(e);S.$('#pointerStatus').textContent=`${Math.round(p.x)}, ${Math.round(p.y)}`;if(!st.isDrawing||!st.pointer)return;st.pointer.current=p;const tool=st.tool;if(['pencil','brush','marker','crayon','airbrush','neon','eraser','fogReveal'].includes(tool)){const l=tool==='fogReveal'?st.project.layers.find(x=>x.kind==='fog'):S.activeLayer();drawSegment(l,st.pointer.last,p,tool);st.pointer.last=p;S.renderLayers();return}if(tool==='lasso'){st.selection.points.push(p);st.selection.x1=p.x;st.selection.y1=p.y;S.renderSelectionOverlay();return}if(tool==='select'){st.selection.x1=p.x;st.selection.y1=p.y;normalizeSelection(st.selection);S.renderSelectionOverlay();return}if(tool==='ruler'){rulerPreview(st.pointer.start,p);return}if(['line','arrow','rect','ellipse','triangle','star'].includes(tool))previewShape(tool,st.pointer.start,p)}
function pointerUp(e){if(!st.isDrawing)return;const p=S.pointerToCanvas(e),tool=st.tool;st.isDrawing=false;if(['pencil','brush','marker','crayon','airbrush','neon','eraser','fogReveal'].includes(tool)){S.autosave?.();return}if(tool==='lasso'){if(st.selection.points.length>2){st.selection.points.push(st.selection.points[0]);S.renderSelectionOverlay()}return}if(tool==='select'){st.selection.x1=p.x;st.selection.y1=p.y;normalizeSelection(st.selection);S.renderSelectionOverlay();return}if(tool==='ruler'){rulerPreview(st.pointer.start,p,true);return}if(['line','arrow','rect','ellipse','triangle','star'].includes(tool)){const l=activeOK();if(!l)return;S.snapshot(`Draw ${tool}`);clearOverlay();paintShape(l.ctx,tool,st.pointer.start,p);S.renderLayers();S.autosave?.()}}
S.bindCanvasTools=function(){const c=O();c.addEventListener('pointerdown',pointerDown);c.addEventListener('pointermove',pointerMove);c.addEventListener('pointerup',pointerUp);c.addEventListener('pointercancel',pointerUp);c.addEventListener('contextmenu',e=>e.preventDefault());c.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();S.zoomTo(st.zoom*(e.deltaY>0?.9:1.1))}},{passive:false})};
})();
