(function(){
'use strict';
const S=window.Savanski,st=S.state;
S.currentWorkspace=()=>S.$('.workspace-tab.active')?.dataset.workspace||'canvas';
S.syncProjectUI=function(){const p=st.project;if(!p)return;S.$('#projectTitleDisplay').textContent=p.name;S.$('#projectName').value=p.name;S.$('#canvasWidth').value=p.width;S.$('#canvasHeight').value=p.height;S.$('#canvasBackground').value=p.background;S.$('#transparentBackground').checked=p.transparent;S.$('#resizeLayerW').value=p.width;S.$('#resizeLayerH').value=p.height;S.$('#canvasStatus').textContent=`${p.width} × ${p.height}`;document.title=`${p.name} — Savanski Art Studio`};
S.syncLayerControls=function(){const l=S.activeLayer();if(!l)return;S.$('#layerOpacity').value=Math.round(l.opacity*100);S.$('#layerOpacityOut').value=Math.round(l.opacity*100);S.$('#layerBlend').value=l.blend||'source-over';S.renderKeyframes?.()};
S.syncMapUI=function(){const m=st.map;S.$('#gridType').value=m.gridType||'square';S.$('#gridSize').value=m.gridSize||70;S.$('#gridOpacity').value=Math.round((m.gridOpacity??.38)*100);S.$('#gridUnits').value=m.units||5;S.$('#gridUnitName').value=m.unitName||'ft';S.$('#exportGrid').checked=m.exportGrid!==false};
S.syncAnimationUI=function(){S.$('#animFrames').value=st.animation.frames;S.$('#animFps').value=st.animation.fps;S.$('#animFrame').max=st.animation.frames-1;S.$('#animFrame').value=st.animation.frame||0;S.$('#animFrameOut').value=st.animation.frame||0;S.renderKeyframes?.()};
S.updateUndoButtons=function(){const u=!st.history.length,r=!st.redo.length;for(const id of ['#undoTop','#undoBtn']){const e=S.$(id);if(e)e.disabled=u}for(const id of ['#redoTop','#redoBtn']){const e=S.$(id);if(e)e.disabled=r}};
function setRangeOut(id,out,suffix=''){const i=S.$(id),o=S.$(out);if(!i||!o)return;const f=()=>o.value=`${i.value}${suffix}`;i.addEventListener('input',f);f()}
function promptNew(){if(st.project&&st.project.layers.some(l=>{try{return l.ctx.getImageData(0,0,Math.min(20,l.canvas.width),Math.min(20,l.canvas.height)).data.some((v,i)=>i%4===3&&v)}catch{return false}})&&!confirm('Start a new project? Unsaved edits may be lost.'))return;S.initProject(+S.$('#canvasWidth').value||1600,+S.$('#canvasHeight').value||900,'Untitled Project');S.fitCanvas();S.setWorkspace('canvas')}
async function openImages(files=null,newProject=false){files=files||await S.openFiles('image/*',true);if(!files.length)return;await S.importImageFiles(files,{newProjectIfEmpty:newProject});S.setWorkspace('canvas');S.fitCanvas()}
async function openProject(files=null){files=files||await S.openFiles('.json,.savanski,.savanski.json,application/json',false);if(files[0])try{await S.openProjectFile(files[0]);S.setWorkspace('canvas')}catch(e){console.error(e);S.toast(e.message||'Could not open project.','error')}}
async function chooseLocalProject(){const list=(await S.listBrowserProjects()).sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''));if(!list.length){S.toast('No locally saved projects yet.');return}const text=list.slice(0,20).map((p,i)=>`${i+1}. ${p.name} — ${(p.updatedAt||'').slice(0,16).replace('T',' ')}`).join('\n');const n=+prompt(`Open which local project?\n\n${text}`);if(n>=1&&n<=Math.min(20,list.length)){await S.loadSerializedProject(list[n-1]);S.setWorkspace('canvas')}}
function menuAt(name,anchor){const pop=S.$('#menuPopup'),defs={
file:[['New project',promptNew],['Open image…',()=>openImages()],['Open project file…',()=>openProject()],['Open local project…',chooseLocalProject],null,['Save in browser',S.saveBrowser],['Download editable project',S.downloadProject],['Save through Google Drive',S.saveProjectDrive],null,['Export PNG',()=>S.exportImage('image/png')],['Export WEBP',()=>S.exportImage('image/webp')]],
edit:[['Undo',S.undo],['Redo',S.redo],null,['Copy selection',()=>S.copySelection(false)],['Cut selection',()=>S.copySelection(true)],['Paste image',S.pasteClipboard],['Clear active layer',S.clearActive]],
image:[['Crop to selection',S.cropSelection],['Remove selected color across layer',S.removeColorGlobal],['Auto enhance',S.autoEnhance],null,['Flip horizontal',()=>S.transformLayer('flipH')],['Flip vertical',()=>S.transformLayer('flipV')]],
layer:[['New layer',()=>S.newLayer('Layer')],['Duplicate layer',S.duplicateActiveLayer],['Delete layer',S.deleteActiveLayer],null,['Move layer up',()=>S.moveLayer(1)],['Move layer down',()=>S.moveLayer(-1)],['Merge down',S.mergeDown]],
map:[['Enable map grid',()=>{st.map.enabled=true;S.applyMapSettings();S.setWorkspace('canvas')}],['Reset fog of war',S.resetFog],['Add lighting layer',S.addLightingLayer],['Browse shared library',()=>S.setWorkspace('library')]],
view:[['Fit canvas',S.fitCanvas],['Zoom in',()=>S.zoomTo(st.zoom*1.2)],['Zoom out',()=>S.zoomTo(st.zoom/1.2)],null,['Toggle toolbox',toggleTools],['Toggle inspector',toggleInspector],['Settings',()=>S.$('#settingsDialog').hidden=false]],
help:[['Quick start',()=>alert('Quick start\n\n1. Open an image or start blank.\n2. Choose a tool on the left.\n3. Layers and effects are on the right.\n4. Use VTT Map for grid/fog/light helpers, Collage for layouts, Animate for layer motion, and 3D for model visuals.\n5. Save locally, download an editable project, or connect Google Drive.')],['About',()=>alert('Savanski Art Studio\nVersion '+S.VERSION+'\nA general-purpose drawing, image editing, collage, VTT map, animation, and 3D visual workspace.')]]};pop.innerHTML='';for(const item of defs[name]||[]){if(!item){pop.append(document.createElement('hr'));continue}const b=document.createElement('button');b.type='button';b.textContent=item[0];b.onclick=()=>{pop.hidden=true;Promise.resolve(item[1]()).catch(e=>S.toast(e.message,'error'))};pop.append(b)}const r=anchor.getBoundingClientRect();pop.style.left=`${Math.min(innerWidth-230,r.left)}px`;pop.style.top=`${r.bottom}px`;pop.hidden=false}
function toggleTools(){const e=S.$('.toolbox'),a=S.$('#app');e.classList.toggle('collapsed');a.classList.toggle('tools-collapsed',e.classList.contains('collapsed'))}
function toggleInspector(){const e=S.$('.inspector'),a=S.$('#app');e.classList.toggle('collapsed');a.classList.toggle('inspector-collapsed',e.classList.contains('collapsed'))}
function bindMenus(){S.$$('.menu-bar button[data-menu]').forEach(b=>b.onclick=()=>menuAt(b.dataset.menu,b));S.$('#mainMenuBtn').onclick=()=>menuAt('file',S.$('#mainMenuBtn'));document.addEventListener('pointerdown',e=>{if(!e.target.closest('.menu-popup')&&!e.target.closest('[data-menu]')&&!e.target.closest('#mainMenuBtn'))S.$('#menuPopup').hidden=true})}
function bindCore(){S.$$('.workspace-tab').forEach(b=>b.onclick=()=>{S.setWorkspace(b.dataset.workspace);if(b.dataset.workspace==='three'){S.initThreeWorkspace();S.three?.resize?.()}if(b.dataset.workspace==='library'&&!S.$('#libraryResults').children.length)S.searchLibrary();if(b.dataset.workspace==='map'){st.map.enabled=true;S.applyMapSettings()}});S.$$('.inspector-tabs button').forEach(b=>b.onclick=()=>S.setInspector(b.dataset.inspector));S.$$('#toolGrid .tool').forEach(b=>b.onclick=()=>{S.setTool(b.dataset.tool);if(['text'].includes(b.dataset.tool))S.setInspector('text');if(['rect','ellipse','triangle','star','line','arrow'].includes(b.dataset.tool))S.setInspector('shape')});
S.$('#collapseTools').onclick=toggleTools;S.$('#collapseInspector').onclick=toggleInspector;S.$('#undoTop').onclick=S.undo;S.$('#redoTop').onclick=S.redo;S.$('#saveLocalTop').onclick=S.saveBrowser;S.$('#settingsBtn').onclick=()=>S.$('#settingsDialog').hidden=false;S.$('#closeSettings').onclick=()=>S.$('#settingsDialog').hidden=true;S.$('#settingsDialog').onclick=e=>{if(e.target===S.$('#settingsDialog'))S.$('#settingsDialog').hidden=true};
S.$('#dismissRotate').onclick=()=>{sessionStorage.setItem('savanski.rotateDismissed','1');S.updateRotateNotice()};setRangeOut('#brushSize','#brushSizeOut');setRangeOut('#brushOpacity','#brushOpacityOut');setRangeOut('#brushSoftness','#brushSoftnessOut');setRangeOut('#removeTolerance','#removeToleranceOut');setRangeOut('#removeStrength','#removeStrengthOut');setRangeOut('#layerOpacity','#layerOpacityOut');setRangeOut('#filterIntensity','#filterIntensityOut');setRangeOut('#collageGap','#collageGapOut');setRangeOut('#collageRadius','#collageRadiusOut');}
function bindCanvas(){S.$('#newProjectBtn').onclick=promptNew;S.$('#importImageBtn').onclick=()=>S.$('#imageFileInput').click();S.$('#imageFileInput').onchange=e=>{openImages([...e.target.files]);e.target.value=''};S.$('#pasteImageBtn').onclick=S.pasteClipboard;S.$('#copySelectionBtn').onclick=()=>S.copySelection(false);S.$('#cutSelectionBtn').onclick=()=>S.copySelection(true);S.$('#cropSelectionBtn').onclick=S.cropSelection;S.$('#selectionShape').onchange=e=>{if(st.selection)st.selection.shape=e.target.value;S.renderSelectionOverlay()};S.$('#zoomInBtn').onclick=()=>S.zoomTo(st.zoom*1.2);S.$('#zoomOutBtn').onclick=()=>S.zoomTo(st.zoom/1.2);S.$('#fitBtn').onclick=S.fitCanvas;S.$('#exportPngBtn').onclick=()=>S.exportImage('image/png');S.$('#exportWebpBtn').onclick=()=>S.exportImage('image/webp');S.$('#removeColorGlobal').onclick=S.removeColorGlobal;S.$('#primaryColor').onchange=e=>{if(st.tool==='eyedropper')S.$('#removeColor').value=e.target.value};}
function bindLayers(){S.$('#addLayerBtn').onclick=()=>S.newLayer('Layer');S.$('#duplicateLayerBtn').onclick=S.duplicateActiveLayer;S.$('#deleteLayerBtn').onclick=S.deleteActiveLayer;S.$('#layerUpBtn').onclick=()=>S.moveLayer(1);S.$('#layerDownBtn').onclick=()=>S.moveLayer(-1);S.$('#mergeDownBtn').onclick=S.mergeDown;S.$('#layerOpacity').oninput=e=>{const l=S.activeLayer();if(l){l.opacity=+e.target.value/100;S.$('#layerOpacityOut').value=e.target.value;S.renderLayers();S.autosave()}};S.$('#layerBlend').onchange=e=>{const l=S.activeLayer();if(l){l.blend=e.target.value;S.renderLayers();S.autosave()}}}
function bindTextShapeFilters(){for(const id of ['#textBold','#textItalic'])S.$(id).onclick=e=>e.currentTarget.classList.toggle('active');S.$('#textUppercase').onclick=()=>{S.$('#textValue').value=S.$('#textValue').value.toUpperCase()};S.$('#addTextCenterBtn').onclick=()=>S.addTextAt(st.project.width/2,st.project.height/2);S.$$('#filterGrid [data-filter]').forEach(b=>b.onclick=()=>S.applyFilter(b.dataset.filter));S.$('#autoEnhanceBtn').onclick=S.autoEnhance;}
function bindTransformProject(){S.$('#flipHorizontalBtn').onclick=()=>S.transformLayer('flipH');S.$('#flipVerticalBtn').onclick=()=>S.transformLayer('flipV');S.$('#rotateLayerBtn').onclick=()=>S.transformLayer('rotate',S.$('#rotateLayerValue').value);S.$('#resizeLayerBtn').onclick=()=>S.resizeLayerContent(+S.$('#resizeLayerW').value,+S.$('#resizeLayerH').value);S.$('#fitLayerBtn').onclick=S.fitActiveLayer;S.$('#resizeCanvasBtn').onclick=()=>S.resizeCanvas(+S.$('#canvasWidth').value,+S.$('#canvasHeight').value,false);S.$('#projectName').oninput=e=>{st.project.name=e.target.value||'Untitled Project';S.syncProjectUI();S.autosave()};S.$('#canvasBackground').oninput=e=>{st.project.background=e.target.value;S.renderLayers();S.autosave()};S.$('#transparentBackground').onchange=e=>{st.project.transparent=e.target.checked;S.renderLayers();S.autosave()};S.$('#downloadProjectBtn').onclick=S.downloadProject;S.$('#projectFileInput').onchange=e=>{openProject([...e.target.files]);e.target.value=''};S.$('#saveDriveBtn').onclick=S.saveProjectDrive;S.$('#connectDriveBtn').onclick=S.connectDrive;S.$('#refreshDriveBtn').onclick=()=>S.refreshStorage().catch(e=>S.toast(e.message,'error'))}
function bindCollageMap(){S.$('#collageFiles').onchange=e=>S.setCollageFiles(e.target.files);S.$$('#collageLayouts [data-layout]').forEach(b=>b.onclick=()=>{S.$$('#collageLayouts button').forEach(x=>x.classList.remove('active'));b.classList.add('active');b.dataset.selected='1'});S.$('#buildCollageBtn').onclick=()=>S.buildCollage(S.$('#collageLayouts button.active')?.dataset.layout||'grid2');for(const id of ['#gridType','#gridSize','#gridOpacity','#gridUnits','#gridUnitName','#exportGrid'])S.$(id).addEventListener(id==='#gridUnitName'?'input':'change',S.applyMapSettings);S.$('#applyMapPreset').onclick=S.applyMapPreset;S.$('#toggleFogBtn').onclick=S.resetFog;S.$('#addLightingLayerBtn').onclick=S.addLightingLayer;S.$('#openLibraryFromMap').onclick=()=>S.setWorkspace('library');S.$('#returnCanvasFromMap').onclick=()=>{st.map.enabled=true;S.applyMapSettings();S.setWorkspace('canvas');S.renderLayers();S.fitCanvas()}}
function bindAnimation(){S.$('#animFrames').onchange=()=>{S.configureAnimation();S.syncAnimationUI()};S.$('#animFps').onchange=S.configureAnimation;S.$('#animFrame').oninput=e=>{S.$('#animFrameOut').value=e.target.value;S.renderAnimationFrame(+e.target.value)};S.$('#addKeyframeBtn').onclick=S.addKeyframe;S.$('#removeKeyframeBtn').onclick=S.removeKeyframe;S.$('#previewAnimationBtn').onclick=S.previewAnimation;S.$('#stopAnimationBtn').onclick=S.stopAnimation;S.$('#exportWebmBtn').onclick=S.exportWebM}
function bindLibrary(){S.$('#librarySearchBtn').onclick=S.searchLibrary;S.$('#librarySearch').onkeydown=e=>{if(e.key==='Enter')S.searchLibrary()};S.$('#libraryType').onchange=S.searchLibrary;S.$('#openSharedDriveBtn').onclick=()=>window.open(SAVANSKI_BACKEND.sharedLibraryDriveUrl,'_blank','noopener,noreferrer')}
function bindThree(){S.$('#modelInput').onchange=e=>{S.initThreeWorkspace();S.import3DFiles(e.target.files);e.target.value=''};S.$('#frame3D').onclick=S.threeFrame;S.$('#toggleWireframe3D').onclick=S.threeToggleWire;S.$('#toggleSpin3D').onclick=S.threeToggleSpin;S.$('#togglePulse3D').onclick=S.threeTogglePulse;S.$('#addLightning3D').onclick=S.threeLightning;S.$('#apply2DTexture3D').onclick=S.apply2DTextureTo3D;S.$('#extract3DTexture2D').onclick=S.extract3DTextureTo2D;S.$('#capture3DToCanvas').onclick=S.capture3D;S.$('#exportGlb').onclick=S.export3D;for(const id of ['#threeColor','#threeMetalness','#threeRoughness','#threeOpacity','#threeDoubleSide'])S.$(id).addEventListener(id==='#threeDoubleSide'?'change':'input',S.threeMaterialUpdate);for(const id of ['#threeBackground','#threeLight'])S.$(id).addEventListener('input',S.threeSceneUpdate);S.bindThreeDrop()}
function bindSettings(){S.$('#themeSelect').value=st.settings.theme;S.$('#autosaveToggle').checked=st.settings.autosave;S.$('#showCheckerToggle').checked=st.settings.checker;S.$('#showRotateToggle').checked=st.settings.showRotate;S.$('#canvasScroller').classList.toggle('no-checker',!st.settings.checker);S.$('#themeSelect').onchange=e=>{st.settings.theme=e.target.value;S.settingsSave()};S.$('#autosaveToggle').onchange=e=>{st.settings.autosave=e.target.checked;S.settingsSave()};S.$('#showCheckerToggle').onchange=e=>{st.settings.checker=e.target.checked;S.$('#canvasScroller').classList.toggle('no-checker',!e.target.checked);S.settingsSave()};S.$('#showRotateToggle').onchange=e=>{st.settings.showRotate=e.target.checked;S.settingsSave();S.updateRotateNotice()}}
function bindWelcome(){const w=S.$('#welcomeDialog');S.$('#welcomeNew').onclick=()=>{w.hidden=true;promptNew()};S.$('#welcomeImage').onchange=async e=>{w.hidden=true;await openImages([...e.target.files],true);e.target.value=''};S.$('#welcomeProject').onchange=async e=>{w.hidden=true;await openProject([...e.target.files]);e.target.value=''};S.$('#welcomeContinue').onclick=async()=>{w.hidden=true;if(!await S.loadBrowser())S.toast('No saved local project found.')};S.$('#showWelcomeAgain').onchange=e=>localStorage.setItem('savanski.showWelcome',e.target.checked?'1':'0')}
function bindDropPaste(){document.addEventListener('dragover',e=>{if([...e.dataTransfer?.types||[]].includes('Files'))e.preventDefault()});document.addEventListener('drop',async e=>{if(e.target.closest('#threeHost'))return;const files=[...e.dataTransfer.files];if(!files.length)return;e.preventDefault();const project=files.find(f=>/\.savanski\.json$|\.savanski$|\.json$/i.test(f.name));if(project){await openProject([project]);return}const imgs=files.filter(f=>f.type.startsWith('image/'));if(imgs.length){await openImages(imgs);return}});document.addEventListener('paste',async e=>{if(S.keyboardEditable())return;const files=[...e.clipboardData.items].filter(i=>i.type.startsWith('image/')).map(i=>i.getAsFile()).filter(Boolean);if(files.length){e.preventDefault();await openImages(files)}})}
function bindKeyboard(){document.addEventListener('keydown',e=>{if(S.keyboardEditable())return;const cmd=e.ctrlKey||e.metaKey,k=e.key.toLowerCase();if(cmd&&k==='z'){e.preventDefault();e.shiftKey?S.redo():S.undo()}else if(cmd&&k==='y'){e.preventDefault();S.redo()}else if(cmd&&k==='s'){e.preventDefault();e.shiftKey?S.downloadProject():S.saveBrowser()}else if(cmd&&k==='c'){e.preventDefault();S.copySelection(false)}else if(cmd&&k==='x'){e.preventDefault();S.copySelection(true)}else if(cmd&&k==='v'){e.preventDefault();S.pasteClipboard()}else if(k==='b')S.setTool('brush');else if(k==='e')S.setTool('eraser');else if(k==='t')S.setTool('text');else if(k==='v')S.setTool('select');else if(k==='i')S.setTool('eyedropper');else if(k==='g')S.setTool('fill');else if(k==='delete')S.clearActive()})}
function pwa(){const b=S.$('#installBtn');if(b)b.hidden=true}
async function init(){S.settingsLoad();S.initProject();S.bindCanvasTools();bindMenus();bindCore();bindCanvas();bindLayers();bindTextShapeFilters();bindTransformProject();bindCollageMap();bindAnimation();bindLibrary();bindThree();bindSettings();bindWelcome();bindDropPaste();bindKeyboard();pwa();S.syncProjectUI();S.syncMapUI();S.syncAnimationUI();S.updateUndoButtons();setTimeout(S.fitCanvas,60);S.updateRotateNotice();const show=localStorage.getItem('savanski.showWelcome')!=='0';S.$('#welcomeDialog').hidden=!show;S.$('#showWelcomeAgain').checked=show;S.$('#welcomeContinue').disabled=!localStorage.getItem('savanski.lastProjectId');S.refreshStorage().catch(()=>{S.$('#storagePill').textContent='Local workspace'});S.status('Ready')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
