(function(){
'use strict';
const A=window.Savanski3D,S=A.state;
function slider(id,out,format){const e=A.$(id),o=A.$(out);if(!e||!o)return;const update=()=>o.textContent=format(+e.value);e.addEventListener('input',update);update()}
function bindUI(){window.SavanskiToolbarMenus?.bind3DNavigation?.(A,S);A.$$('[data-primitive]').forEach(b=>b.onclick=()=>A.addPrimitive(b.dataset.primitive));A.$$('[data-transform]').forEach(b=>b.onclick=()=>A.setTransformMode(b.dataset.transform));A.$('#frameBtn').onclick=()=>A.frameObject();A.$('#resetViewBtn').onclick=()=>A.frameAll();A.$('#gridBtn').onclick=()=>{S.grid.visible=!S.grid.visible;A.$('#gridBtn').setAttribute('aria-pressed',String(S.grid.visible))};A.$('#wireBtn').onclick=A.toggleWire;A.$('#toonBtn').onclick=A.toggleToon;A.$('#duplicateBtn').onclick=A.duplicateSelected;A.$('#deleteBtn').onclick=A.deleteSelected;A.$('#u3dUndoBtn').onclick=A.undo;A.$('#u3dRedoBtn').onclick=A.redo;A.$('#simplifyBtn').onclick=A.simplifySelected;A.$('#tessellateBtn').onclick=A.tessellateSelected;A.$('#weldBtn').onclick=A.weldVertices;A.$('#normalsBtn').onclick=A.recomputeNormals;A.$('#mirrorBtn').onclick=A.mirrorSelected;A.$('#centerPivotBtn').onclick=A.centerPivot;A.$('#mergeVisibleBtn').onclick=A.mergeVisible;A.$('#applyTransformBtn').onclick=A.applyTransform;slider('#simplifyAmount','#simplifyOut',v=>v+'%');slider('#tessellateEdge','#tessellateOut',v=>(v/100).toFixed(2));slider('#sculptRadius','#sculptRadiusOut',v=>(v/100).toFixed(2));slider('#sculptStrength','#sculptStrengthOut',v=>(v/100).toFixed(2));slider('#sculptHardness','#sculptHardnessOut',v=>(v/100).toFixed(2));slider('#paintSize','#paintSizeOut',v=>v+'px');slider('#paintOpacity','#paintOpacityOut',v=>v+'%');slider('#lightIntensity','#lightOut',v=>(v/100).toFixed(1));slider('#hemiIntensity','#hemiOut',v=>(v/100).toFixed(1));
  A.$$('[data-transform-input]').forEach(e=>{e.addEventListener('focus',()=>A.pushHistory('Numeric transform'),{once:false});e.addEventListener('change',ev=>A.handleTransformInput(ev.target))});A.$('#objectName').onchange=e=>{if(!S.selected)return;A.pushHistory('Rename object');S.selected.name=e.target.value;A.refreshSceneList();A.syncInspector()};A.$('#objectVisible').onchange=e=>{if(!S.selected)return;A.pushHistory('Visibility');S.selected.visible=e.target.checked;A.refreshSceneList()};A.$('#objectCastShadow').onchange=e=>{if(!S.selected)return;A.pushHistory('Shadow setting');S.selected.castShadow=e.target.checked};
  const matControls=['#materialColor','#materialMetalness','#materialRoughness','#materialOpacity','#materialStyle','#doubleSide','#wireMaterial'];for(const q of matControls){const e=A.$(q);e.addEventListener('change',A.updateMaterialFromUI)}for(const [q,out] of [['#materialMetalness','#metalOut'],['#materialRoughness','#roughOut'],['#materialOpacity','#opacityOut']])A.$(q).addEventListener('input',e=>A.$(out).textContent=(+e.target.value/100).toFixed(2));A.$('#removeTextureBtn').onclick=()=>{const o=S.selected;if(!o?.isMesh)return;A.pushHistory('Remove texture');const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>{m.map=null;m.needsUpdate=true});A.toast('Base texture removed','success')};
  A.$('#sceneBackground').oninput=e=>S.scene.background.set(e.target.value);A.$('#lightIntensity').oninput=e=>{S.key.intensity=+e.target.value/100;A.$('#lightOut').textContent=S.key.intensity.toFixed(1)};A.$('#hemiIntensity').oninput=e=>{S.hemi.intensity=+e.target.value/100;A.$('#hemiOut').textContent=S.hemi.intensity.toFixed(1)};A.$('#sceneSearch').oninput=A.refreshSceneList;
  A.$('#importBtn').onclick=()=>{if(window.SavanskiProjectLibrary)return window.SavanskiProjectLibrary.openHome('3d',{intent:'import'});A.$('#modelInput').click()};A.$('#modelInput').onchange=async e=>{const files=e.target.files;if(files?.length)await A.importFiles(files);e.target.value='';window.dispatchEvent(new CustomEvent('savanski:3d-import-complete'))};A.$('#u3dNewProjectBtn').onclick=()=>{if(window.SavanskiProjectLibrary)return window.SavanskiProjectLibrary.openHome('3d',{intent:'new'});window.dispatchEvent(new CustomEvent('savanski:home-request'))};A.$('#exportProjectBtn').onclick=A.exportProject;A.$('#exportGlbBtn').onclick=A.exportGLB;A.$('#exportObjBtn').onclick=A.exportOBJ;A.$('#exportStlBtn').onclick=A.exportSTL;A.$('#exportPlyBtn').onclick=A.exportPLY;A.$('#saveLocalBtn').onclick=()=>window.SavanskiProjectLibrary?.save3D?.()||A.exportProject();
  const shell=A.$('#viewportShell');['dragenter','dragover'].forEach(n=>shell.addEventListener(n,e=>{e.preventDefault();A.$('#dropOverlay').classList.add('show')}));['dragleave','drop'].forEach(n=>shell.addEventListener(n,e=>{e.preventDefault();A.$('#dropOverlay').classList.remove('show')}));shell.addEventListener('drop',e=>A.importFiles(e.dataTransfer.files));
  A.$('#u3dThemeBtn').onclick=()=>document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';A.$('#helpBtn').onclick=()=>A.$('#helpModal').classList.add('show');A.$('#closeHelpBtn').onclick=()=>A.$('#helpModal').classList.remove('show');A.$('#helpModal').onclick=e=>{if(e.target.id==='helpModal')e.currentTarget.classList.remove('show')};
  window.addEventListener('keydown',e=>{if(document.body.dataset.workspace!=='3d')return;const typing=/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName||'');if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?A.redo():A.undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();A.redo();return}if(e.key==='Escape'){A.$('#helpModal')?.classList.remove('show');if(S.sculpt)A.setSculptMode(false);if(S.directPaint)A.setDirectPaint(false);return}if(typing)return;if(e.key.toLowerCase()==='w')A.setTransformMode('translate');else if(e.key.toLowerCase()==='e')A.setTransformMode('rotate');else if(e.key.toLowerCase()==='r')A.setTransformMode('scale');else if(e.key.toLowerCase()==='f')A.frameObject();else if(e.key==='Delete'||e.key==='Backspace')A.deleteSelected()});
}
async function boot(){try{A.initScene();bindUI();A.initSculpt();A.initPaint();A.initAvatar();A.initCapture();A.updateHistoryButtons();const [baseOk,proOk]=await Promise.all([window.SavanskiWasm.init(),window.SavanskiProfessionalWasm?.init?.()??Promise.resolve(false)]);A.$('#wasmStatus').textContent=(baseOk||proOk)?'WASM: active':'WASM: JS fallback';A.$('#wasmStatus').title=(baseOk||proOk)?'Compiled WebAssembly mesh kernels are active':'Browser could not initialize the bundled kernels; equivalent JavaScript fallbacks remain available';A.clearRoot();A.$('#projectName').value='No project open';S.undo.length=S.redo.length=0;A.updateHistoryButtons();A.status('Ready — open or create a 3D project from Home.');window.dispatchEvent(new CustomEvent('savanski:3d-ready'))}catch(e){console.error(e);A.status('Studio failed to initialize');A.toast('Initialization failed: '+e.message,'error')}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
