'use strict';
const assert=require('node:assert/strict');
const {seededRandom}=require('./determinism');
const {FixedStepClock}=require('./world-tick');
const {AOIGrid}=require('./aoi-grid');
const {TokenBucket,CommandGate}=require('./commands');
const {QuestMachine}=require('./quest-state');
const {Ledger,weightedPick,craft}=require('./economy');
const {resolveAbility}=require('./combat');
const {formMatch}=require('./matchmaking');
const {checksum,migrate}=require('./persistence');
const {MessageGuard,permissionsFor}=require('./social-safety');
assert.equal(seededRandom(1)(),seededRandom(1)());
let tick=0;const clock=new FixedStepClock({stepMs:50,maxCatchUpSteps:2,onStep:()=>tick++});assert.equal(clock.advance(200).steps,2);assert.equal(tick,2);assert.equal(clock.droppedMs,100);
const grid=new AOIGrid(10);grid.upsert('a',-1,-1);grid.upsert('b',20,20);assert.equal(grid.query(-1,-1,3).length,1);grid.remove('a');assert.equal(grid.query(-1,-1,3).length,0);
let time=0;const bucket=new TokenBucket({capacity:2,refillPerSecond:1,now:()=>time});assert(bucket.take('p'));assert(bucket.take('p'));assert(!bucket.take('p'));time=1000;assert(bucket.take('p'));
const gate=new CommandGate({maxStep:10});assert(gate.accept({actor:'p',seq:1,kind:'use'}).ok);assert.equal(gate.accept({actor:'p',seq:1,kind:'use'}).reason,'stale-sequence');
const q=new QuestMachine({id:'q',states:['open','done'],start:'open',complete:'done',transitions:[['open','done']]});q.begin('p');q.transition('p','done','event1');q.transition('p','done','event1');assert.equal(q.snapshot('p').revision,1);
const ledger=new Ledger();ledger.open('mint',{allowNegative:true});ledger.open('purse');ledger.post({key:'grant',entries:[{account:'mint',currency:'coin',amount:-5},{account:'purse',currency:'coin',amount:5}]});assert.equal(ledger.balance('purse','coin'),5);assert.throws(()=>ledger.post({key:'bad',entries:[{account:'purse',currency:'coin',amount:-8},{account:'mint',currency:'coin',amount:7}]}));assert.equal(ledger.balance('purse','coin'),5);
assert.equal(weightedPick([{value:'x',weight:1}],()=>0.5),'x');assert(craft({wood:2},{id:'r',inputs:{wood:2},outputs:{bow:1}}).ok);assert(!craft({wood:1},{id:'r',inputs:{wood:2},outputs:{bow:1}}).ok);
assert.equal(resolveAbility({actor:{energy:3},target:{},ability:{id:'a',power:4,cost:1},now:0,random:()=>0.5}).amount,4);
const match=formMatch([{id:'a',rating:1,ping:10,joinedAt:0},{id:'b',rating:2,ping:10,joinedAt:0}],{teamSize:1,now:1000,skillSpread:10});assert(match);
assert.equal(checksum({b:2,a:1}),checksum({a:1,b:2}));assert.equal(migrate({version:0,state:{n:1}},1,{0:s=>({n:s.n+1})}).state.n,2);
assert(new MessageGuard().inspect('p','hello').allow);assert(permissionsFor('leader').has('guild.transfer'));
console.log('MMO brain self-test passed');
